### ISSUE TITLE
ES6/7/8 and the future of JavaScript

### ISSUE THREAD

**Issue by ifrit** [dcjs/talks#12]
Your Name: Alexander Saify  
Your twitter handle: ifrit
A few words about yourself: Long time programmer and recent React proselytizer with a penchant for design. I spend my summers planning for That Thing in the Desert.

Talk title: **ES6/7/8 and the future of JavaScript** [WORKING TITLE]

Talk abstract:  
A deep dive into the new language features available to developers, both now (through babel) and in the near future. This will be a dig into the more non-trivial aspects of how the JavaScript language is changing. Examples will be provided using React + Node.js.

Expected length: 45m - 1h

Available months: Aug, October, November, December
- Thu Aug 11 2016
- Thu Oct 13 2016
- Thu Nov 10 2016
- Thu Dec 08 2016

**Comment by jakerella** [comment]
Very popular concept these days! In fact, John K Paul just did a similar topic for the ReactDC meetup! I'm open to this, but could you flesh out the topics a bit more?

I'd also probably prefer just core JS (versus examples in React) as that adds a layer of complexity that might make it difficult to follow the main points of ES6/7/8. Thoughts?

**Comment by ifrit** [comment]
Ideally I'd like to do it in pure JS. The mention of React was more to put it into context for developers who enjoy real world examples. Let me flesh it out a bit tonight.

**Comment by jakerella** [comment]
Awesome, thanks! And I think relating it to React (or any other framework) is cool, just wanted to keep it a bit generic for folks _not_ using one of those frameworks.

**Comment by lizafloyd** [comment]
Hey @ifrit , wondering what you're thinking of discussing as "non-trivial aspects"? Trying to get a good sense of what to expect here! Thanks, looking forward!
