### ISSUE TITLE
Getting started with GraphQL

### ISSUE THREAD

**Issue by ramsaylanier** [dcjs/talks#13]
Your Name: Ramsay Lanier
Your twitter handle: rmmmsy
A few words about yourself: I'm a senior developer at nclud.

Talk title: Getting started with GraphQL using [Apollo Stack](http://apollostack.com)

Talk abstract:  
My talk would start with an introduction to GraphQL and why/how it could be a replacement for REST APIs. I'll discuss the GraphQL type language, defining a GraphQL schema, connecting it to a database (or many databases), and fetching data on the client. To illustrate these points, I'll be using Apollo Stack.

"Apollo is an incrementally-adoptable data stack that manages the flow of data between clients and backends. Based on GraphQL, it gives you a principled, unified, and scalable API for developing modern apps on top of services."

Expected length: 30-45 min

Available months: Not July, Not November

**Comment by d6u** [comment]
😍  is it possible to speak more about plain GraphQL setup without any abstraction layers, so people can learn more about the foundation? I'm know nothing about the Apollo Stack FYI. Also talking about gradually introducing GraphQL into existing REST setup is useful.

**Comment by ramsaylanier** [comment]
Apollo just makes it easier to connect server and client to a GraphQL schema. I'd definitely start with the basics of writing GraphQL schemas, connectors, and resolvers. Those are all "stack agnostic", meaning Apollo wouldn't come into play there.

**Comment by jakerella** [comment]
Sounds neat! I would definitely like to see this kept more focused on front end development (and JS, obviously), but it looks promising.

**Comment by jakerella** [comment]
Do you know if this is closer to 30 min or closer to 45? We need to know what else we could fit into a meetup with this talk (basically, two short sessions, or a single long one).

**Comment by ramsaylanier** [comment]
@jakerella I can make it either, though 45 minutes would allow me to cover more things, and in more detail. I'm flexible though.

**Comment by jakerella** [comment]
Awesome, thanks! We'll when we can fit this in.

**Comment by jakerella** [comment]
Hey @ramsaylanier! We're hoping you would be available September 8 to do this talk for DCJS. Are you available?

**Comment by jakerella** [comment]
This talk is being delivered at the October meeting.
