### ISSUE TITLE
What's new in D3.js 4.0

### ISSUE THREAD

**Issue by fillerwriter** [dcjs/talks#14]
Your Name: Brandon Morrison
Your twitter handle: @fillerwriter
A few words about yourself: Brandon Morrison is a software engineer based in the Washington DC area. He specializes in developing intricate web applications and informative data visualizations. While open to a variety of projects, Brandon's technical chops lean toward Angular, D3, NodeJS, and PHP.

Brandon contributes a fair amount of code to the open source community, including the Drupal Geofield module and GeocoderJS. In addition, he speaks at meetups and conferences on mapping and development topics.

Talk title: What's new in D3.js 4.0

Talk abstract:  _Note: I'm giving this talk at Tech Fusion in July, but I'd love another opportunity to present in DC proper_ http://www.meetup.com/Tech_Fusion/events/232415766/

D3.js is a fantastic library for building data visualizations with Javascript. The library recently had a 4.0 release with quite a few changes, including immutable selections, better modularity, and several tweaks to make rendering to canvas significantly easier. Join us as we cover what's new and what's changed in D3. 

While this talk is geared towards people who have some experience with D3, we'll do our best to make it accessible for those who will be exposed to D3 for the first time.

Expected length: 30-60min

Available months: Anytime

**Comment by jakerella** [comment]
Sounds good... I think doing a solid intro to D3 would be good as well. I'm concerned that a lot of people won't even know what you use D3 for. ;)

**Comment by jakerella** [comment]
Can we narrow down that expected length? That's a big range for one meetup! Basically, we need to know if it's a long session or one which we can combine to have a dual-talk meeting.

**Comment by fillerwriter** [comment]
I'm flexible. If you want to have someone double-up with me, I'm happy to give a 30 minute presentation. I'm also happy to take a full presentation. If we go with the shorter presentation, I'd want to focus on either "What is D3?" (more introductory) or "What's new in D3?" (more intermediate) instead of cramming both in.

**Comment by jakerella** [comment]
Cool. I'll label this with both and we can figure it out later.

**Comment by jakerella** [comment]
Hi @fillerwriter! Any chance you can give this talk on September 8?

**Comment by fillerwriter** [comment]
Unfortunately, I have plans that date. Maybe the following month?

**Comment by jakerella** [comment]
That's too bad! We'll definitely get it in some time, we don't have the plan for October yet, but we'll try to work that out shortly.

**Comment by jakerella** [comment]
Hi! So we were hoping you could deliver this in November, would you be free? It would be November 10.

**Comment by fillerwriter** [comment]
Sounds good to me. Should I plan on this being a full session or a half-session?

**Comment by jakerella** [comment]
Awesome! A full session, but maybe 45 minutes? I was thinking about throwing in a short talk before yours.

**Comment by jakerella** [comment]
https://www.meetup.com/DC-JavaScript/events/235185256/
