### ISSUE TITLE
Angular 2 CLI

### ISSUE THREAD

**Issue by samiam151** [dcjs/talks#16]
Your Name: Nicolas Sam
Your twitter handle: [@samiam1512](http://twiiter.com/samiam1512)
A few words about yourself: Aspiring Front End Developer

Talk title: Angular 2 CLI (working title)

Talk abstract:  
Setting up a new Angular2 application can be cumbersome, and definitely time-consuming. We need to setup app files, Typescript configs, Typescript typings, testing frameworks, System.js configs and more, and we haven't even said 'Hello!' to the world yet! In comes Angular CLI! This talk aims to introduce the CLI tool for creating, scaffolding, and building ng2 applications. 

Notes:
Although there is a similar tool for ng1, I won't go into that. I plan to have a slide on what Angular is (for the uninitiated), and a slide about what you need to get a ng2 app started, just to show how beneficial the CLI is. Most of the talk will be about initializing a new project and what the tool sets up for you; this could easily fill up 15-20 minutes. Additionally, I can go into one or two other commands that adds a new component or route, time permitting.

Expected length: 15-20 minutes
Available months: Anytime

**Comment by jakerella** [comment]
I think this is a great idea for a short talk. We might be able to work this into the beginning of a meeting where we have a not-terribly-long main talk, or some month where we do a set up lightning talks as our meetup!

In terms of content, your abstract is already pretty solid. I'm not sure what else to throw in there for a shorter talk! Do you have any questions about what to cover or the process?

**Comment by samiam151** [comment]
I think I'll stick with that! If any other ideas come up while I'm working on it, I'll give a shout!

**Comment by jakerella** [comment]
@samiam151 We have a short slot on Sep 8 before the main talk of the night... do you want to present this topic then?

**Comment by jakerella** [comment]
Hi Nicolas! With Angular 2 out for real now I we were hoping you could do this short talk for us in November (the 10th). We would have another speaker after you, so we'd have to keep it around 10-15 minutes, is that doable?

**Comment by samiam151** [comment]
That sounds good! I'll put that down.

On Sun, Oct 2, 2016 at 10:04 AM, Jordan Kasper notifications@github.com
wrote:

Hi Nicolas! With Angular 2 out for real now I we were hoping you could do
this short talk for us in November (the 10th). We would have another
speaker after you, so we'd have to keep it around 10-15 minutes, is that
doable?

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
https://github.com/dcjs/talks/issues/16#issuecomment-250972809, or mute
the thread

**Comment by jakerella** [comment]
https://www.meetup.com/DC-JavaScript/events/235185256/
