### ISSUE TITLE
Talk about ECMAScript 6 (formerly "WANTED")

### ISSUE THREAD

**Issue by elgreg** [dcjs/talks#17]
We'd love to have someone come and talk through using ES6 but without trying to explain React at the same time. Maybe a "you don't need underscore/lodash anymore" talk?

Interested? Know someone who might be? Just comment on this issue!

**Comment by christine-sm** [comment]
Hi there! I just attended the most recent meetup last week. I'd be happy to co-present on this topic with somebody else. I am fairly comfortable with ES6, but I am not super familiar with how it compares to underscore/lodash (limited experience with both of those).

**Comment by jakerella** [comment]
Hi @cmmovius! There is no specific need to compare/contrast with _any_ other library, but it was a thought. Basically, JS devs have been using libraries to do a lot of the things that ES6 does "out of the box" now, so it would be great to mention some of those particular features.

If you want to find a co-presenter, that's great! If not, we can certainly help you develop the talk yourself. I'd be happy to review an outline or slides, and you are welcome to practice the talk on me (or my class of new front-enders at The Iron Yard).

Let us know!

**Comment by christine-sm** [comment]
Hi @jakerella! If we can go over slides and/or practice beforehand, then I would be happy to present on my own :smile: When are you targeting the next meetup date to be? Mid-October?

**Comment by jakerella** [comment]
We always do talks the second Thursday of the month. That said, October is booked. :)

I'll chat with the other organizers about November soon, but there are some other talks submitted as well. If you're willing to do this one we'll make sure it gets on the schedule soon!

**Comment by christine-sm** [comment]
Sounds good! This will give me more time to prepare.

**Comment by shade-tree-software** [comment]
Hey Christine, I recently gave an introductory ES2015 talk at my company.  I'd be happy to do something similar with you at DCJS or help you prepare your own talk or answer any questions you might have.

Andy

**Comment by christine-sm** [comment]
Hi Andy, thank you for reaching out. What resources did you find helpful when preparing to give your talk?

**Comment by shade-tree-software** [comment]
Mostly I used my class notes from an ES2015 course that I took a while
back.  But I also used the documentation on developer.mozilla.org for the
stuff I wasn't too clear on.  If you'd like to see the topics I talked
about, feel free to check out my powerpoint slides at
github.com/shade-tree-software/ES2015.  The slides don't have a lot of
detail, though, because I spent most of my talk writing and running actual
code.  I only used the slides to introduce the topics.

Andy

**Comment by christine-sm** [comment]
Thank you for sharing; I just took a look through the slides. I had no idea that ES2015 has hash maps! I will have to explore that functionality this week.

At this point, I have decided that I would like to give this presentation on my own, as it will be a good challenge and learning experience. But I really appreciate the help you have provided thus far and hopefully I'll see you at the meetup!

**Comment by shade-tree-software** [comment]
Great!  Looking forward to it :)

**Comment by jakerella** [comment]
@cmmovius When you get to that point, can you provide us the typical abstract talk submission info? See below:

Your Name: [Your name]  
Your twitter handle: [optional]  
A few words about yourself: [why you do what you do, how you came to be filling this out, star wars vs star trek, etc., etc.]

Talk title: [Or just the topic if you don't have one yet]

Talk abstract:  
[A longer description of what you'd like to speak about goes here... you can revise this over time!]

Expected length: [Example: 45mins; use a range if your'e flexible]

Available months: [Example: July, Aug, Sept | Example: Not October | Example: All of them]

_We meet on the second Thursday of the month generally. You can use this handy-dandy list to check dates:_
- Thu Nov 10 2016
- Thu Dec 08 2016
- Thu Jan 12 2016
- Thu Feb 9 2016
- Thu Mar 9 2016

**Comment by christine-sm** [comment]
Your Name: Christine Movius

Your twitter handle: @cmmovius

A few words about yourself: Christine Movius is a GIS Application Developer based in Washington, DC. She creates web maps for mission-driven organizations, with a focus on visualizing data in fields such as education and the environment. In her former lives she was an actor and a Fulbright Grantee in Malaysia.

Talk title: ES6 Sans React (working title)

Talk abstract:

ECMAScript 6 is often presented in conjunction with React. However, you do not need to use React to take advantage of the new features of ES6, including:
- Declaring variables using `let` and `const`
- Template Strings
- Arrow Functions `=>`
- Default Function Parameters
- Classes
- Iterables
- …Spread and …Rest
- Array and Object Destructuring
- Object Initializer Shorthand
- and more!

Expected length: 45 minutes - 1 hour

Available months: November (although I see D3/Angular 2 CLI will probably be then!), December, January, February. Not March.

**Comment by jakerella** [comment]
This is a great start! And yes, November we've just nailed down.

On the abstract, bullet points can be handy in moderation, but could you "sentencize" that a bit more? Remember, this is intended to "sell" your talk to a potential audience. I think (personally) you can just leave off the React bit and talk about all the cool ES6 features, but maybe add a bit about why people should care?

**Comment by christine-sm** [comment]
Sounds good. I will make adjustments this week!

**Comment by christine-sm** [comment]
Hey @jakerella here is an updated abstract. Let me know what you think!

ECMAScript2015 (6th Edition) or “ES6” for short, is a major update to the implementation of JavaScript. ES6 provides additional features to JavaScript––such as improved variable scope and Classes––that every Javascript developer can take advantage of! In this presentation, we will cover many of the new features in ES6, and how to compile ES6 code into ES5 using Babel so you can use it in current web browsers.

**Comment by jakerella** [comment]
Sounds good!

**Comment by christine-sm** [comment]
@jakerella here are my updates!

Your Name: Christine Movius

Your twitter handle: @cmmovius

A few words about yourself: Christine Movius is a GIS Application Developer based in Washington, DC. She creates dynamic mapping applications for mission-driven organizations, with a focus on visualizing data in fields such as education and the environment. In her former lives she was an actor and a Fulbright Grantee in Malaysia.

Talk title: ES6 Essentials

Talk abstract:
Are you a recent coding bootcamp grad who is looking to take their JavaScript skills to the next level? Are you a seasoned JavaScript developer who is looking to write cleaner, more concise code? Then come on over for an evening of ES6 and empanadas.
ECMAScript2015 (6th Edition) or “ES6” for short, is a major update to the implementation of JavaScript. ES6 provides additional features to JavaScript––such as improved variable scope and Classes––that every Javascript developer can take advantage of. In this presentation, we will cover many of the new features in ES6, and provide resources for continued training.
