### ISSUE TITLE
`<noscript>` is Dead! Using JavaScript to improve the accessible user experience.

### ISSUE THREAD

**Issue by karlgroves** [dcjs/talks#19]
Your Name: Karl Groves
Your twitter handle: karlgroves
A few words about yourself: I think that the Star Wars prequels get a bad rap, but is Jar Jar Binks really any worse than C3PO? They're both bumbling fools the only difference is that someone actually programmed C3PO to be an annoying twit.

Talk title: `<noscript>` is Dead! Using JavaScript to improve the accessible user experience.

Talk abstract:  
Through examples and demonstrations, Karl Groves will blather on for 45-60 minutes about accessibility. Hopefully you'll learn something in the process and hopefully what you learn is that JavaScript is awesome and doesn't pose a meaningful issue for accessibility once you learn to keep it in mind as you develop.  

This will show ways to use JavaScript in ways that improve the experience for the user. For instance, providing Audio Description to videos using the MediaController API, using Live Regions to notify users of content changes, and things like that.

Expected length: 45-60 mins

Available months: September, October, definitely not November

**Comment by jakerella** [comment]
@karlgroves Thanks for the submission! Can you expand much on the abstract? What's the expected content you'll cover?

**Comment by karlgroves** [comment]
This will show ways to use JavaScript in ways that improve the experience for the user. For instance, providing Audio Description to videos using the MediaController API, using Live Regions to notify users of content changes, and things like that.

**Comment by jakerella** [comment]
Awesome. FYI, I wasn't just asking for me. :) We would also want to use that description in the abstract we post to the meetup site. Can you update the initial issue description?

**Comment by jakerella** [comment]
Hi Karl! Can we get an update on the "official" abstract for the talk?

**Comment by jakerella** [comment]
Are you able to give this talk January 10?

**Comment by karlgroves** [comment]
Sorry for the delay. Had to check schedules with the wife. ;-)

Yes, I can do Jan 10.

Karl

**Comment by jakerella** [comment]
Great!! We'll get that event set up and announce it at the December meetup next week.

**Comment by jakerella** [comment]
@karlgroves OMGOMGOMG... I am SO sorry... I totally misread the calendar. DCJS is supposed to be THURSDAY, JANUARY 12!

Any chance you can still do that??
