### ISSUE TITLE
Move scheduled talk directories into single "talks" directory

### ISSUE THREAD

**Issue by jakerella** [dcjs/talks#2]
In order to preserve the readability of the main directory, I'd like to move the specific scheduled/completed talk directories into a general `talks` directory. So the current structure would become:
- talks
  - 20160616-html5-jkasper
    - READEME.md
    - announcement.md
  - 20140714-tbd-dcousineau
- ISSUE_TEMPLATE.md
- README.md
- speaker-primer.md

@asabaylus @elgreg Any concerns with that?

**Comment by elgreg** [comment]
Sounds good to me.
