### ISSUE TITLE
Talk Proposal: Arabic internationalization

### ISSUE THREAD

**Issue by mapmeld** [dcjs/talks#21]
Your Name: Nick Doiron
Your twitter handle: @mapmeld
A few words about yourself: traveling web developer and mapmaker, previously with Code for America, One Laptop per Child, and the Museum of Modern Art. I recently created the right-to-left language layout for the OpenStreetMap editor.

Talk title: Arabic internationalization

Talk abstract:  
Practical examples of supporting Arabic script on the web, with these examples:
- webfonts and Arabic basics (how to tell if your words are showing up correctly)
- right-to-left HTML and CSS for Carter Center app
- zero-width join and "stretch Arabic"
- considerations in Canvas, SVG, and maps

Expected length: flexible

Available months: December - ?

**Comment by jakerella** [comment]
What's the expected length here? We'll be doing lightning talks in February and if you think this could fit into 10 minutes or less we can do it then. If you feel this should have a longer slot then we'll give it a look for a future month.

**Comment by mapmeld** [comment]
I could do 8-10min, but February might be too soon; I'm traveling until Feb
27. Would the March meetup be possible (before March 20th?)

**Comment by jakerella** [comment]
Well, the idea was to fit this into our "lightning talk" meetup, which is February 9. We haven't started the scheduling for any later months yet! We'll keep it in the queue for review though!

**Comment by mapmeld** [comment]
I've (mostly) moved back to DC! Let me know if this would be good sometime soon

**Comment by jakerella** [comment]
Hi @mapmeld! We have a speaker for August, but we'd love to have you do this short session beforehand. Can you keep it to 10 min or so? (No hard limit)

**Comment by mapmeld** [comment]
What day in August? I might be at Gerrymandering Summer School in Boston (Aug 7-11)

**Comment by jakerella** [comment]
Ack! Yes, it would be Aug 10. We'll have to look for another date then.

**Comment by mapmeld** [comment]
closing until I move back to DC
