### ISSUE TITLE
Introduction to Three.js and WebGL

### ISSUE THREAD

**Issue by rpchurchill** [dcjs/talks#22]
Your Name: R.P. (Bob) Churchill
bob@rpchurchill.com
www.rpchurchill.com

Your twitter handle: none

A few words about yourself: I'm a long-time mechanical engineer, process analyst, and technical software developer specializing in simulation, real-time computing, control systems, and informational graphics.

Talk title: Introduction to Three.js and WebGL (and even Virtual Reality!) 

Talk abstract:  
The first online tutorials for the Three.js framework are super easy and approachable and about a zillion people have generated online materials telling you what to do.  However, there is less material available after the bare beginnings.  I'll walk though the next few steps that will allow you to do something more interesting, show you how to avoid some of the pitfalls, and describe the (very basic) underlying theory.  I'll do all of this while explaining how I incorporated the framework into the modular discrete-event simulation system I'm building (in JavaScript for now).  As a kicker, depending on the amount of time I'm given, I'll also describe how to (easily!) turn it all into something that can be viewed in Virtual reality.  I'll pass around my phone in a VR headset.  The Bluetooth controller I have won't talk to the phone through the Gamepad API or anything in JavaScript that I've found, so that part is out. 
 
Expected length: 15-30 minutes.  I'm flexible.

Available months: Any time, starting in February 2017.  Just give me two days notice.

![des-20170110](https://cloud.githubusercontent.com/assets/19749611/21829955/7a322930-d767-11e6-8d03-8f6725352c65.png)

**Comment by rpchurchill** [comment]
I gave this talk in Baltimore on February 1st and it went over reasonably well.  Let me know if you have any trouble viewing the slides here:

[https://slides.com/qulatan/deck/fullscreen/](https://slides.com/qulatan/deck/fullscreen/)

I may make a couple of brief additions but the point is that it's ready to go when you are..

**Comment by jakerella** [comment]
Neat! Thanks... how long was that session?

**Comment by rpchurchill** [comment]
About 20 minutes.  Maybe less.

**Comment by jakerella** [comment]
Cool... We might take that and throw it in front of another talk in April or May if you're up for it!

**Comment by jakerella** [comment]
Hi there @rpchurchill! It's been a while, sorry. We tend to lose track of things. Would you be up for doing this on April 12? Trying to line things up in advance.

**Comment by rpchurchill** [comment]
Sure, love to.  Thanks.

Just on the fly-the-by I put together (and gave in Baltimore) an additional presentation on memory management in JavaScript compared to traditional compiled languages.  See http://rpchurchill.com/presentations/JavaScriptMemoryMgt/

I'm probably going to modify it a little bit more.  I can write it up as a separate entry if you'd like.
