### ISSUE TITLE
Using JOI on the client and server

### ISSUE THREAD

**Issue by jreading** [dcjs/talks#23]
Your Name: John Reading
Your twitter handle: johnnyreading
A few words about yourself: A full-stack javascript masquerading as a Software Engineering Manager for Morningstar

Talk title: Using JOI for shared schemas across app, web and db tier.

Talk abstract: At Morningstar we use an innersource framework called Capitol Framework that uses JOI from Walmart labs that was designed to provide schema validation for REST endpoints. We also use these schemas with adapters to create rich data models for Ember Data, and types in sequelize for use in MySQL and MongoDB.

Learn how we leverage this schema approach to gain a trusted relationship across all tiers of the application.

Expected length: 10 mins

Available months: April, May, June

**Comment by jakerella** [comment]
Talked to John, he's going to try to get this into Feb. for lightning talks.
