### ISSUE TITLE
Javascript for Sound Art

### ISSUE THREAD

**Issue by nvioli** [dcjs/talks#28]
Your Name: Nick Violi
Your twitter handle: nvioli
A few words about yourself: Hi, I'm Nick. I've been programming in various capacities for 10+ years (well, I guess if you want to reach back to my TI-83 days it's more than that, but I'd rather not date myself). I've been working as a capital-P programmer for the last 4+, hired as a full-stack engineer, but focusing on frontend development for the last 2.5 or so. I've been friends with @elgreg for around 10 years, but I just started attending DCJS in the last few months. I've learned some good stuff every time I join you and I think it would be fun to give a talk; it seems like a great way to learn a new topic, and practicing public speaking is a bonus.

Talk title: Javascript for Art; or How to p5js; or somesuch...

Talk abstract:
I've been playing around with Processing's javascript library, [p5js](https://p5js.org/), and I think it would make an interesting talk. My first foray was building [this little experiment](https://nvioli.github.io) (you'll need to accept the microphone permission), but my goal for the next step is to hook up a visualization to a prerecorded sound file or sample library. I read this [great tutorial on generative music in javascript](https://teropa.info/blog/2016/07/28/javascript-systems-music.html), and this feels like a natural extension.

If that sounds reasonable I think I'll just start building it, keep good notes, and build the talk in parallel as I learn and make some decisions. Do you think it would work best as a sort of show-and-tell, where I start with the finished product and then break down some of the interesting components? Or is there a better way to think about it?

I'd appreciate any guidance you have about the scope or structure of a talk like this. Any tips you have to give me the best chance of making something that people will enjoy and get the most out of would be great!

Expected length: 45ish minutes sounds about right.

Available months: I'm proposing two talks; the first would probably be ready July - September, or maybe later, and the second some time after that. Please let me know which of the two sounds more interesting / more likely to make a talk that people enjoy and get something out of.

**Comment by elgreg** [comment]
Chatted with @jakerella about this and I think we're both equally pumped about the sound presentation. When are you thinking? July?

**Comment by nvioli** [comment]
I picked a topic and set up my dev environment, so I'm basically like 90% done.
</jokes>

July might be a bit ambitious; I'll see how far I get in the next few weeks and keep you posted.

**Comment by jakerella** [comment]
July is taken now. :) So is September, and I'm not sure about August... @elgreg or @asabaylus did we check on August?

**Comment by elgreg** [comment]
Accepted for September!

**Comment by jakerella** [comment]
Hey @nvioli! Just making sure that you are still good for September 14. Let us know and we'll get the meetup invite out!

**Comment by nvioli** [comment]
Yep yep! Hard at work on the presentation. The working title is "Web Audio
+ Visualizations with p5.js", or feel free to use whatever you think is
best.

Looking forward to it!

**Comment by jakerella** [comment]
That's bit of a mouthful. :) What about the original title above? I don't think you need to be so specific in the title. Anyway, we're super excited!! Once you have the title and abstract nailed down let's get the event posted. Let me know if you need any help!

**Comment by nvioli** [comment]
Sure, title of the issue is fine too.

Here's a quick swing at an abstract:
Javascript isn't just for building forms and making divs appear and disappear! In our September meetup, Nick will introduce p5.js, a powerful yet approachable library geared towards artists and beginner programmers. P5 supplies the browser with components for drawing and manipulating shapes, building animations, creating and playing sounds, and more.

Nick will work through a small project he built interpreting a piece of 20th century classical music, with short forays into music theory, the math behind it, and their relationship to programming.

Improvements & suggestions welcome :)

**Comment by jakerella** [comment]
I love it! Let's run with it. I'll get the meetup event set.

**Comment by nvioli** [comment]
Just checking in, haven't seen the event yet. Also I was talking to Greg about speakers (being an audio presentation and all). He suggested a Bluetooth one but I wonder if anyone has access to a better setup? I'll ask around too...

**Comment by elgreg** [comment]
Thanks for the prod! It is scheduled and announced as of a few minutes ago!

I wish we had a PA. Alas, no dice. Not sure if anyone is working for a
place that has one or could provide one. I'll ask around.

**Comment by jakerella** [comment]
I can bring some logitech speakers to connect to your computer... not great, but better than the laptop speakers. No mic. Let me know

**Comment by asabaylus** [comment]
I've got a pretty loud Bluetooth nose speaker that I think may work

**Comment by nvioli** [comment]
Cool, thanks guys, sounds like we have some options. I have a pair of Sonos
speakers that are quite loud, but don't have a line in. I was doing some
reading about casting from a computer and found some leads that I'll play
around with when I'm home. If that doesn't work maybe we can all just bring
what we have and figure out the best solution when we get there.

**Comment by asabaylus** [comment]
Hi Nick have you looked at air parrot?
http://www.airsquirrels.com/airparrot/

It may do the trick for streaming to your sonos speakers

Asa

**Comment by nvioli** [comment]
Thanks, Asa. I'll check that out.

**Comment by nvioli** [comment]
Hey guys, just want to finish up the speaker conversation. The Sonos thing isn't going to work. I borrowed a small set of Logitech speakers, but is it annoying if I ask you both (Asa and Jake) to bring the speakers you have and we can just figure out the best solution before the presentation?

**Comment by asabaylus** [comment]
Sure the speaker I have may be too small but I'll bring it no harm in trying

Asa

**Comment by elgreg** [comment]
I have a pretty loud bluetooth one that I'll bring as well. I'll try to get
there by 5:30pm or 6 so that we can test it out without disrupting too much.

**Comment by asabaylus** [comment]
I think we should be able to use ampme to share Bluetooth across multiple speakers https://www.techforpc.com/tag/ampme-for-windows-and-mac/

**Comment by jakerella** [comment]
Do we have a final solution? @nvioli ?

**Comment by nvioli** [comment]
@jakerella I think we have some good options and we should just all bring them and find the best combination a few minutes beforehand. If it's a pain for you to bring yours nbd.

**Comment by jakerella** [comment]
Mine is a fairly big setup (all the speakers plug into the subwoofer). If we think that's the best option I am happy to bring it, just need to know if there are other good options.

**Comment by nvioli** [comment]
Ooh, if yours has a dedicated sub I think that sounds like the best option...
