### ISSUE TITLE
A talk about svelte.js

### ISSUE THREAD

**Issue by nvioli** [dcjs/talks#29]
Your Name: Nick Violi
Your twitter handle: nvioli
A few words about yourself: Hi, I'm Nick. I've been programming in various capacities for 10+ years (well, I guess if you want to reach back to my TI-83 days it's more than that, but I'd rather not date myself). I've been working fulltime as a capital-P programmer for the last 4+, hired as a full-stack engineer, but focusing on frontend development for the last 2.5 or so. I've been friends with @elgreg for around 10 years, but I just started attending DCJS in the last few months. I've learned some good stuff every time I join you and I think it would be fun to give a talk; it seems like a great way to learn a new topic, and practicing public speaking is a bonus.

Talk title: svelte.js and then some more words

Talk abstract:
Through some path or retweets or mutual follows or something in the Twitter frontend engineer space, I started following [@Rich_Harris](https://twitter.com/Rich_Harris) a few months ago. Since then, I've been following his path through launching and promoting [svelte](https://svelte.technology/). To be honest I haven't made it farther than the marketing boilerplate and hello world examples, but I think putting together a talk about it would be a great way to learn the framework.

Unless you all have any great suggestions for how to structure a talk like this, or some of your favorite examples of talks about frameworks that I could base mine on, I'm picturing just putting together an example app--a to-do list, or maybe a mock shopping website or something--and using that example to talk through the technology, some of its interesting features and quirks, etc.

As in the other talk, any advice or guidance you have is welcome!

Expected length: 45ish minutes sounds about right.

Available months: I'm proposing two talks; the first would probably be ready July - September, or maybe later, and the second some time after that. Please let me know which of the two sounds more interesting / more likely to make a talk that people enjoy and get something out of.

**Comment by jakerella** [comment]
I think you have a hidden gem in here... " a talk about it would be a great way to learn the framework." What if the talk was ABOUT learning a new framework? In other words, with all of them that we have these days, how _should_ a developer ramp up in a new framework?

**Comment by jakerella** [comment]
ping... never heard a response to my comment/thought. In any case, is this still a talk you're interested in delivering?

**Comment by nvioli** [comment]
This one didn't really come together and I'm more interested in https://github.com/dcjs/talks/issues/53 right now.

**Comment by jakerella** [comment]
:+1:
