### ISSUE TITLE
Web Performance Auditing

### ISSUE THREAD

**Issue by uncompiled** [dcjs/talks#30]
**Your Name**: Chris Nguyen
**Your twitter handle**: [@uncompiled](https://twitter.com/uncompiled)
**A few words about yourself**: I'm a backend developer disguised in web developer clothing.  I've been in the tech industry for a while, but now I develop platform software for the web.  I haven't seen much talk about web performance in the area, so I thought I'd give it a shot.

**Talk title**: Navigating the Critical Path: A Journey in Web Performance

**Talk abstract**:  
- What is web performance and why does it matter? (keep it short)
- The usual metrics: page load, time to first paint, time to interactive
- Performance tooling: a walkthrough of available methods and tools to gather performance metrics

**Expected length**: 30-45 minutes

**Available months:** (May or later)

**Comment by elgreg** [comment]
This sounds like a great idea! We definitely could use more talks about performance and optimization.

**Comment by jakerella** [comment]
👍

**Comment by uncompiled** [comment]
Thanks!  I'll start putting this together. 🎉

**Comment by jakerella** [comment]
Let us know if this is leaning toward 30 min or 45... we have 1 or 2 shorter talks (20-30 min) and we might put two in one night.

**Comment by uncompiled** [comment]
I can do 30 minutes.

**Comment by jakerella** [comment]
Cool cool... we've got things through September right now, but let's chat about doing this one in the Fall.
