### ISSUE TITLE
[ON HOLD] JavaScript on JavaScript: how the parser & generator ecosystem makes new things possible

### ISSUE THREAD

**Issue by tmcw** [dcjs/talks#32]
Your Name: Tom MacWright
Your twitter handle: tmcw
A few words about yourself: I'm a freerange tinkerer and open source maintainer, currently spending time learning and building projects including [simple statistics](http://simplestatistics.org/) and [documentation.js](http://documentation.js.org/). Previously, I built mapping software at Mapbox

Talk title: JavaScript on JavaScript: how the parser & generator ecosystem makes new things possible

Talk abstract:  
The rise of Babel and other tools that transpile JavaScript between versions has given birth to an ecosystem of parsers, generators, and analysis utilities that let you treat JavaScript code as data and build new static analysis software much more rapidly. I'll discuss how this is central to documentation.js and makes tools like [code-spell-check](https://github.com/mapbox/code-spell-check) and zero-code CLIs possible.

Expected length: ~30mins

Available months: May, June, July

_We meet on the second Thursday of the month generally. You can use this handy-dandy list to check dates:_

- [ ]  Thu Apr 13 2017
- [ ] Thu May 11 2017
- [ ] Thu Jun 08 2017
- [ ] Thu Jul 13 2017
- [ ] Thu Aug 10 2017
- [x] Thu Sep 14 2017
- [ ] Thu Oct 12 2017
- [ ] Thu Nov 09 2017
- [ ] Thu Dec 14 2017

**Comment by asabaylus** [comment]
@tmcw thanks for submitting, I'd definitely like to get you setup with a date! Your past talks at DCJS were a big hit, glad to have you come back.

**Comment by asabaylus** [comment]
@tmcw how's Sep 14th or Oct 12th work for you?

**Comment by tmcw** [comment]
September 14th works great for me

**Comment by asabaylus** [comment]
@tmcw we're booking you for Sept 14th, thanks!

**Comment by tmcw** [comment]
So, change in plans: I'm moving out of the DC area in August, so I won't be able to give this talk in September. Sorry about that!

**Comment by jakerella** [comment]
Noooooo! Dang man, well... hope it's a good move for you.

Let us know when you might be back in town and we can try to work this in. I'll mark it as "on hold" for now... unless you want us to close it.

**Comment by jakerella** [comment]
Closing the issue for now, but let us know if you make it back to DC!
