### ISSUE TITLE
React 101

### ISSUE THREAD

**Issue by ghost** [dcjs/talks#35]
Your Name: Janice Gluck  
Your twitter handle: @JumpinJanice (but I don't really use twitter)
A few words about yourself:  Lead Engineer with lots of experience in a wide range of technologies and applications.   I build software because its my calling in life and I love doing it.  The best part of being a software engineer is learning new technologies and applying them to real world problems.  React is a great tool for modernizing the application I work on since it allows us to improve things incrementally.

Talk title: React 101

Talk abstract:  
React is a very cool javascript library... very easy to pick up and great when you need to revise the UI of a website incrementally.    It allows you to build very nice components to make your code reusable and easy to understand.   I will be aiming to give folks an overview of how to use react with thoughts on how to make your code production quality for the long haul.  I will also have code samples and a demo or two.  Topics include:  (order is not final )

1. about react
2. install
3. build tools ( webpack, es6, babel, etc)
3. JSX
4. simple component demo
5. state vs props 
6. composing components
7. higher order components
8. redux
9.  Error handling
10. Logging, Metrics, production deployment, maintenance (may or may not include depending on length of presentation)

Expected length: 30 mins?? - can be flexible

Available months:  July

_We meet on the second Thursday of the month generally. You can use this handy-dandy list to check dates:_

- [ ] Thu Jun 08 2017
- [x] Thu Jul 13 2017
- [ ] Thu Aug 10 2017
- [ ] Thu Sep 14 2017
- [ ] Thu Oct 12 2017
- [ ] Thu Nov 09 2017
- [ ] Thu Dec 14 2017
- [ ] Thu Jan 11 2018
- [ ] Thu Feb 08 2018
- [ ] Thu Mar 08 2018
- [ ] Thu Apr 12 2018

**Comment by jakerella** [comment]
w00t!

We're planning this for July, correct?

**Comment by ghost** [comment]
I am planning on it for July.

**Comment by asabaylus** [comment]
@jumpinjan when you get a chance can you add a synopsis so we can promote the talk on React?

**Comment by jakerella** [comment]
This is up on meetup!

https://www.meetup.com/DC-JavaScript/events/240606440/

**Comment by ghost** [comment]
Great!   But I work for Hobsons not Nat Geo

Thanks
Janice

Sent from my iPhone

On Jun 20, 2017, at 6:07 PM, Jordan Kasper <notifications@github.com<mailto:notifications@github.com>> wrote:


This is up on meetup!

https://www.meetup.com/DC-JavaScript/events/240606440/

**Comment by jakerella** [comment]
ACK! Fixing now....
