### ISSUE TITLE
GunJS: Up and Running

### ISSUE THREAD

**Issue by sjones6** [dcjs/talks#36]
Your Name: Spencer Jones
Your twitter handle: jones_spencera
A few words about yourself: I write proprietary software by day in Herndon, and open source by night. Contributor to GunJS. Building arsenalio.com.

Talk title: GunJS: Up and Running (provisional title)

Talk abstract:  
GunJS is a realtime, offline-first, peer-to-peer graph database written in JavaScript—it's kind of like an open-source FireBase. This talk will spend 10-15 mins overviewing how Gun works and how its data is structured (a graph). The rest of the talk will be a demonstration of Gun on both the backend (in Node) and frontend (plain JS, or possibly Vue). 

First, I will demonstrate wiring up a Gun server with Express, and attaching Gun to a Mongo database for long-term persistence. Second, I will wire up the frontend code to communicate with the Gun server and retrieve data in real-time. The presentation will finish by "deploying" three Gun servers in Docker containers, demonstrating how high-availability and data replication can be achieved with Gun.

Expected length: 30-45mins

Available months: July, Aug, Sept are probably best but Nov-Jan are available too

_We meet on the second Thursday of the month generally. You can use this handy-dandy list to check dates:_

- [ ] Thu Jun 08 2017
- [X] Thu Jul 13 2017
- [X] Thu Aug 10 2017
- [X] Thu Sep 14 2017
- [ ] Thu Oct 12 2017
- [X] Thu Nov 09 2017
- [X] Thu Dec 14 2017
- [X] Thu Jan 11 2018
- [ ] Thu Feb 08 2018
- [ ] Thu Mar 08 2018
- [ ] Thu Apr 12 2018

**Comment by jakerella** [comment]
Crazy! We'll look this over and get back to you. A bit more in the abstract would help though!

**Comment by sjones6** [comment]
@jakerella : I've updated the abstract with some more details on what the talk would look like. Let me know if that helps!

**Comment by jakerella** [comment]
You're talk is up! Be sure to RSVP: https://www.meetup.com/DC-JavaScript/events/244605651/
