### ISSUE TITLE
How To Get the Most Value out of Code Reviews

### ISSUE THREAD

**Issue by kscoulter** [dcjs/talks#38]
Your Name: Ksenia Coulter  
Your twitter handle: @kscoult

Bio: Neuroscientist turned coder, Ksenia is a front end web developer at Washington Post. She is passionate about making DC tech a supportive, inclusive community for everyone. In her spare time she dances swing, plays obscure boardgames, and gives excellent pep talks to all who need them.

Talk title: How To Get the Most Value out of Code Reviews

Talk abstract:  
There is an inherent hierarchy to a typical code review – the code reviewer has some authority over the one being reviewed. This dynamic can lead to unnecessary tension and a shutdown of open communication on your team (humans are notoriously bad at giving and receiving feedback). But this dynamic plays out only if you view the role of a code reviewer as a gatekeeper guarding the code base from the reviewee. What if I told you there is another way?

During this talk, we will reassess the purpose of the code review. How do we judge “good code”? What does it mean for code to be maintainable? How do we create a culture of trust where feedback is not painful? Using real examples and code snippets, we will discuss ways to use the code review process to improve your code base, reaffirm your team values, and promote a culture of learning. 

Expected length: 20-30 minutes

Available months: Not September, December or January.

_We meet on the second Thursday of the month generally. You can use this handy-dandy list to check dates:_

- [ ] Thu Sep 14 2017
- [x] Thu Oct 12 2017
- [x] Thu Nov 09 2017
- [ ] Thu Dec 14 2017
- [ ] Thu Jan 11 2018
- [x] Thu Feb 08 2018
- [x] Thu Mar 08 2018
- [x] Thu Apr 12 2018

**Comment by jakerella** [comment]
I think this sounds great! It would be great if we could focus on examples in front end code... but I get that this isn't really a code-heavy talk.

**Comment by jakerella** [comment]
Oh, and being 20-30 minutes, we'll probably do a double-talk night when we do this, FYI.

**Comment by kscoulter** [comment]
@jakerella, just saw this! Yes, the talk has multiple front-end examples.

**Comment by jakerella** [comment]
Hi @kscoulter! I know Liza reached out to you, we're creating the meetup invite now, but just confirming here that you're good with January 11! (I ask because I notice on here it literally says _not January_.)
