### ISSUE TITLE
Code Linting and Formatting

### ISSUE THREAD

**Issue by freestylebit** [dcjs/talks#39]
Your Name: Peter Cho
Your twitter handle: @freestylebit
A few words about yourself: Finally finished season 3 of Game of Thrones, early adopter of HD-DVDs, terrible at secret identity games.

Talk title: Automatic Code Styling in Less Than 58 seconds

Talk abstract:
Want to introduce to the community some relatively quick and easy ways to incorporate linting and code style formatters into their workflow to improve readability and also save time.  Tools of note would include `eslint`, `prettier`, and plugins that integrate with modules from npm.

Will include some demos to demonstrate automatic code fixes, syntax highlighting, and a couple more things.

Expected length: 10-15 min (or shorter; would prefer this to be a lightning talk)

Available months:

- [X] Thu Sep 14, 2017
- [ ] October 12, 2017
- [X] and beyond...

**Comment by jakerella** [comment]
Hey Peter! Just an FYI, we're waiting on a month when we have a shorter talk that we can put this in front of, or an all lightning talk month. That said, we're all up for having it!

**Comment by freestylebit** [comment]
I will get to work on a prototype for this talk this weekend.  Was planning to scope this under 10 minutes, but if we need this to be expanded, I can add a few extra things, too.

**Comment by jakerella** [comment]
Hey there @freestylebit! Did you ever give this one? I don't recall seeing it... but I also missed a couple meetups for work travel. If not, would you want to do it in August for our lightning talk event?

**Comment by freestylebit** [comment]
I don't think I did.  I can review what I have and make updates to it before August 9 (if that's the official date).  As far as I know, I can drop by that night!

**Comment by jakerella** [comment]
It is the official date! Glad to hear you're up for it.
