### ISSUE TITLE
How to think like a computer scientist

### ISSUE THREAD

**Issue by jakerella** [dcjs/talks#4]
Your Name: Daniel Cousineau  
Your twitter handle: @dcousineau

Talk title: How to think like a computer scientist

Talk abstract:  
Often times, we hit a wall and get stuck on a problem, only to realize much later - and after lengthy and unnecessary pain- that the solution was simple if we had just reframed the problem as something else. Thinking like a Computer Scientist involves being able to take a step back, abstracting what we know about a problem space, and realizing relations to other, solved, problems that were not, and come away with that "aha!" moment that we all know and love immediately apparent. Together, we'll tackle a problem and along the way learn how to think as developers.

Expected length: 50 min

Available months: July

Speaker bio:  
Daniel Cousineau is a Senior Frontend Engineer for Grovo living in New York City. In his laughably short free time he volunteers as a ScriptEducator, co-organizes the QueensJS user group, co-organizes the EmpireJS & Lone Star PHP conferences, and does not enjoy long walks on the beach because walking on sand is a tough workout for your inner thighs. He is Yolo Certified and despite his last name not Canadian.

**Comment by jakerella** [comment]
@dcousineau Can you add an abstract for us?

**Comment by dcousineau** [comment]
@jakerella 

> Often times, we hit a wall and get stuck on a problem, only to realize much later - and after lengthy and unnecessary pain- that the solution was simple if we had just reframed the problem as something else. Thinking like a Computer Scientist involves being able to take a step back, abstracting what we know about a problem space, and realizing relations to other, solved, problems that were not, and come away with that "aha!" moment that we all know and love immediately apparent. Together, we'll tackle a problem and along the way learn how to think as developers.

**Comment by jakerella** [comment]
👍 Thanks!

@dcousineau: can you give us a short bio as well?

@elgreg @asabaylus Any other questions?

**Comment by dcousineau** [comment]
@jakerella 

> Daniel Cousineau is a Senior Frontend Engineer for Grovo living in New York City. In his laughably short free time he volunteers as a ScriptEducator, co-organizes the QueensJS user group, co-organizes the EmpireJS & Lone Star PHP conferences, and does not enjoy long walks on the beach because walking on sand is a tough workout for your inner thighs. He is Yolo Certified and despite his last name not Canadian.

**Comment by elgreg** [comment]
zomg great bio.

**Comment by elgreg** [comment]
Let's post this thang. @jakerella I'll give you meetup access, too. :) @asabaylus thou art the Slack-admin. Please also add Jordan. Grazié

**Comment by asabaylus** [comment]
I think its Jesse Shawl who owns the slack channel, I've asked him to transfer it my way. Also 👍 great bio

**Comment by jakerella** [comment]
Cool. Let's get the meetup posted. @elgreg or @asabaylus ... do you want me to do that? We can use the same location for the July meetup, in August we'll be in our new location and will have lots of space and chairs and such.

**Comment by asabaylus** [comment]
@elgreg posted it the other day http://www.meetup.com/DC-JavaScript/events/232044665/

**Comment by jakerella** [comment]
heh... just saw that. We can update the location to the same as last month... I'll do that.

**Comment by elgreg** [comment]
I'll pull the tigger on announcing this now.

**Comment by jakerella** [comment]
👍 
When should we close this issue? I suppose when #11 is merged?
