### ISSUE TITLE
Styling your React App using Styled Components

### ISSUE THREAD

**Issue by tommymarshall** [dcjs/talks#40]
**Name:** Tommy Marshall
**Twitter handle:** [@tommyjmarshall](https://twitter.com/tommyjmarshall)
**A few words about myself:** Northern Virginia native, GMU Economics grad, loves building things on the web. 
**Website:** [tommyjm.com](http://tommyjm.com)

## Talk title
Six reasons why you should be using Styled Components

## Talk abstract:  
Styling JavaScript apps is deceitfully hard. With so many different packages, implementations, and opinions, it's hard to know which one works best for you. In this talk, I'll show how we went from using a webpack loader to [classnames](https://github.com/JedWatson/classnames) to finally using [Styled Components](https://www.styled-components.com), and why we're loving it so far.

## Expected length:
25-30minutes, 15minutes of QA and live demoing

## Timeframe to present
- [ ] Thu Feb 08 2018
- [X] Thu Mar 08 2018
- [X] Thu Apr 12 2018

**Comment by tommymarshall** [comment]
Up. :)

**Comment by tommymarshall** [comment]
I'll be presenting this to React DC looks like. Perhaps I can do a GraphQL one for DC JS soon!

**Comment by jakerella** [comment]
Happy to hear that you'll be giving it regardless! Thanks anyway

**Comment by tommymarshall** [comment]
@jakerella The talk was pretty successful. [Here are the slides](http://slides.com/tommymarshall/styled-components). Wouldn't mind giving the presentation again for DCJS. What do you think?

**Comment by lizafloyd** [comment]
Hey @tommymarshall your slides look really interesting! You're availability is still good through the spring? Thanks!

**Comment by tommymarshall** [comment]
@lizafloyd Would love to! Sign me up 👍

**Comment by lizafloyd** [comment]
Hi @tommymarshall how's our Feb meetup, on Thursday the 8th, 6:30 event start, talk at 7?

**Comment by tommymarshall** [comment]
Followed up via email!

**Comment by jakerella** [comment]
Hey there! Was that only to Liza? I don't think I'm on that chain. In any case, would you be available March 8?

**Comment by tommymarshall** [comment]
@jakerella correct -- @lizafloyd and I followed up with each other via email. I can confirm I can speak March 8th. Our Tyson's office cannot host this time, sadly, but will be able to in the future.
