### ISSUE TITLE
A Walk Through The Glimmer Virtual Machine

### ISSUE THREAD

**Issue by chadhietala** [dcjs/talks#41]
Your Name: Chad Hietala  
Your twitter handle: chadhietala
A few words about yourself: I'm a Senior Staff Engineer at LinkedIn that primarily works on open source solutions. I'm also on the Ember Core Team.
Talk title: A Walkthrough The Glimmer Virtual Machine

Talk abstract:  
Over the past 2 years I've worked on the rendering engine that is used in Ember and Glimmer applications. Unlike majority of UI frameworks today, the rendering engine is not a Virtual DOM implementation, but rather a virtual machine implementation. In this presentation I will talk about the design decisions we made, a quick overview of the compiler and runtime stacks, and how the VM stacks up against other UI solutions.

Expected length: 35 - 45min

Available months: October (except the week of the 23rd), November

_We meet on the second Thursday of the month generally. You can use this handy-dandy list to check dates:_

- [x] Thu Oct 12 2017
- [x] Thu Nov 09 2017
- [x] Thu Dec 14 2017
- [ ] Thu Jan 11 2018
- [x] Thu Feb 08 2018
- [x] Thu Mar 08 2018
- [ ] Thu Apr 12 2018

**Comment by chadhietala** [comment]
There is likely more to this talk since we have now landed the ability to compile templates into a binary format and currently working on a WebAssembly implementation with the folks at Tilde and Mozilla.

**Comment by jakerella** [comment]
Sweet! We've got people for March and April, but maybe May or June? Need to chat with the other organizers too.

**Comment by chadhietala** [comment]
June is the last month I will be living in DC so likely the only option if the other spots are filled.
