### ISSUE TITLE
Orchestrated and Serverless Micro-services in the Cloud - JavaScript Case Study from PBS KIDS

### ISSUE THREAD

**Issue by aberkie** [dcjs/talks#42]
Your Name: Aaron Berkowitz
Your twitter handle: asberk

A few words about yourself: Hello! I am the Director of Technology at PBS KIDS. My team and I use JavaScript to architect solutions for products and solutions for children, parents, and teachers across the country. We are looking to share our experience, get feedback, and meet developers in the community.

Talk title: Orchestrated and Serverless Micro-services in the Cloud - JavaScript Case Study from PBS KIDS (Working title...?)

Talk abstract:  
For a recent project, PBS KIDS Engineering developed a system to send text messages to parents using AWS Lambda and Step Functions. The result is a completely serverless, highly scaleable, system completely written in JavaScript. Attendees should come away with an understanding of how to create and deploy orchestrated JavaScript microservices in the cloud without much dev-ops knowledge.

Expected length: 45 minutes - 1 Hour

_We meet on the second Thursday of the month generally. You can use this handy-dandy list to check dates:_

Any date works for me! 

- [X] Thu Jun 08 2017
- [x] Thu Jul 13 2017
- [X] Thu Aug 10 2017
- [x] Thu Sep 14 2017
- [x] Thu Oct 12 2017
- [x] Thu Nov 09 2017
- [x] Thu Dec 14 2017
- [x] Thu Jan 11 2018
- [x] Thu Feb 08 2018
- [x] Thu Mar 08 2018
- [x] Thu Apr 12 2018

**Comment by jakerella** [comment]
Hi Aaron! So sorry for the long delay here, I think we just got caught up in some other talks, and then we had the one event at NPR (trying to spread the love).

Would you be available to do this talk either September 13 or October 11?

**Comment by jakerella** [comment]
ping? Any chance you're free to do this talk Oct 11?

**Comment by aberkie** [comment]
Hey @jakerella - sure, October 11 works. Do you have the time and place details?

**Comment by jakerella** [comment]
Great! We're working out the location. We held it at Chief last week and we're hoping to do so again, but they may have a conflict. I'll jot you down in the schedule and get the meetup event out soon!

Thanks a ton!!

**Comment by jakerella** [comment]
Hi @aberkie! Are you ready for this week? Anything you need or questions?

See you Thursday at the Chief offices!

**Comment by aberkie** [comment]
Hey @jakerella - yep, all set! Is there an HDMI hookup with audio?

**Comment by jakerella** [comment]
Thank you sir!
