### ISSUE TITLE
An Introduction to Typescript

### ISSUE THREAD

**Issue by kkrivera** [dcjs/talks#45]
Your Name: Kris Rivera
Your twitter handle: N/A
A few words about yourself: I am a Senior Software Engineer of 11 years and love working on personal projects. I own my own company and have developed 2 games with my partner. I am also a black belt in Shudokan Karate and enjoy playing basketball.

Talk title: An Introduction to Typescript

Talk abstract:  
This will be a talk about introducing Typescript to the JS developers in our community. I will be providing a brief overview of the history of Javascript, going from ES5, moving to ES6 and what was introduced there, and then spending the bulk of the time reviewing Typescript, what this offers as a superset of ES5 and ES6, as well as some of the basics of the language.

Expected length: 30-45min

Available months: All Months (except for Feb 8-10 and March 14-16)

_We meet on the second Thursday of the month generally. You can use this handy-dandy list to check dates:_

- [] Thu Jan 11 2018
- [ ] Thu Feb 08 2018
- [X] Thu Mar 08 2018
- [X] Thu Apr 12 2018
- [X] Thu May 10 2018
- [X] Thu Jun 07 2018
- [x] Thu Jul 12 2018
- [x] Thu Aug 09 2018
- [x] Thu Sep 13 2018
- [x] Thu Oct 11 2018
- [x] Thu Nov 08 2018
- [x] Thu Dec 13 2018

**Comment by lizafloyd** [comment]
Looks very cool @kkrivera , thanks for submitting! Can you give me a sense of what you're thinking of discussing in the "basics of the language" section? Just to flesh out my understanding of what to expect. Thanks!

**Comment by kkrivera** [comment]
Hi Liza,

Yes, on microsoft's Typescript wiki page (
https://github.com/Microsoft/TypeScript/wiki), there is a section for
Language Basics.
Depending on how much time I am allowed, I would consider covering up Basic
Types, Interfaces, Classes, Namespaces and Modules, and Functions. I was
planning on making an 'advanced typescript' session as well, at a later
date, as well as an interactive talk on setting up a typescript project in
nodejs.

Let me know if you need any further information

Kris

**Comment by jorgeso** [comment]
I just suggested this same talk to Gregg. I've been using Typescript for over a year now, and have fallen in love with the language. Let me know if you want to collaborate or need any help with organizing this.

This is a good podcast that gave me the idea on presenting on the subject:

https://softwareengineeringdaily.com/2017/08/11/typescript-at-slack-with-felix-rieseberg/

**Comment by kkrivera** [comment]
I am actually in the process of writing this presentation and will be
presenting this at the Vue.js meetup next week 4/16 at the Bloombery BNA
building at 6:30pm. Feel free to come by and let me know if you have any
further suggestions for a follow up talk/collaboration as well.

**Comment by kkrivera** [comment]
@lizafloyd here is the link to my slides. If you guys are still interested, I just presented these slides to a VueJS meetup last night. https://bit.ly/2wUTiVA

**Comment by elgreg** [comment]
This looks great! Does September work for you? Any interest in working with @jorgeso to maybe have a night of typescript?

**Comment by kkrivera** [comment]
September would be great! And yes, I would love to to work with @jorgeso

**Comment by jakerella** [comment]
Hey folks! Are you still on for September?

@jorgeso and @kkrivera let me know if so, it would be September 13. Let us know if this is a joint effort, or if you each have a 30 or so min talk and we can split the night. Thanks!

**Comment by jakerella** [comment]
ping... is this mic on?

I'm going to start asking some other folks about September 13, so let me know soon!

**Comment by kkrivera** [comment]
I am so sorry. I totally thought that I had responded to this email. My
apologies. Yes, I am available for Sep 13 to provide an Intro to Typescript
talk. I already have my slides ready to go. Please let me know further
details. If necessary, I can easily fill 45minutes, but i can try to keep
it down to 30 minutes.

Again, sorry

Kris

**Comment by jorgeso** [comment]
Sorry about this. Recently changed jobs and I forgot to update my email on Github. Looks like Kris already has a presentation ready to go and can easily go the hour so I would say just go for it. If you really want to split it or make it a joint presentation, I’m open to it as well. We would just have to plan it. So let me know.

**Comment by jakerella** [comment]
Thanks fellas! No worries on the delay. We have you (Kris) down for Sep 13, but @jorgeso, if you have some nuance you wanted to talk about that's not in Kris' presentation we could do a split show. In that case, I think we keep Kris' to 30 min and give Jorge 15. Otherwise we'll give Kris a full 45.

Let me know! We'll get the meetup event posted soon.

**Comment by kkrivera** [comment]
Here is the link for my slides. Let me know if you have any questions
https://drive.google.com/open?id=107Y2EP2p_f8_3QEnYFRTfwblKPcXC5BTPSzzqYSvDFE

**Comment by jakerella** [comment]
Awesome, thanks!

**Comment by jorgeso** [comment]
@kkrivera deck looks good. Hard to cover everything about TypeScript in one 45-minute presentation, but you’ve covered A great deal. If you have any live examples, it would be cool to show them some of the tools you can use with VS code - like go to definition, find all references, rename symbol, etc.

Either way, I think you have it covered, so I’ll just step aside, but I’ll try to make it and see it.

**Comment by kkrivera** [comment]
Hi all,

I wanted to know what time and where on the 13th I will be presenting

Thanks,
Kris

**Comment by jakerella** [comment]
Hey! The meetup is slated for 6:30pm, but we usually have a little welcoming bit at first. You should plan to start around 7pm. (But get there early if you want empanadas, they run out!)

**Comment by kkrivera** [comment]
Awesome. Thank you so much. I will plan to be there at 6:30
