### ISSUE TITLE
Intro to GatsbyJS

### ISSUE THREAD

**Issue by mandy6720** [dcjs/talks#46]
Your Name: Amanda Bozzi

Your twitter handle: apiamanda

A few words about yourself: I'm a JavaScript engineer at SBD2, on a government contract that's a ground up re-write of PECOS, the tool healthcare providers use to register for accepting Medicare/Medicaid. I'm here, filling this out because I was contacted by Liza, who found me on WeSpeakToo and asked if I had any talks I wanted to share. I like glitter, junk food and videos of funny animals on the internet. I also like JavaScript 🙃

Talk title: Intro to Gatsby - A static site generator (SSG) made with React and GraphQL

Talk abstract:  
This talk will be about [Gatsby](https://www.gatsbyjs.org/), self-described as a "Blazing-fast static site generator for React". I will begin with what a SSG is and why you might consider using one and an overview of how they work. Then, I will discuss the building blocks of Gatsby - React, Webpack and GraphQL. I'll dive a little deeper into GraphQL (and show an example of why it's so cool - at least it is in my opinion 😄). I'll close with the pros and cons of Gatsby and then take questions.

Expected length: ~30-45mins

Available months: All of them

_We meet on the second Thursday of the month generally. You can use this handy-dandy list to check dates:_

- [ ] Thu Jan 11 2018
- [ ] Thu Feb 08 2018
- [x] Thu Mar 08 2018
- [x] Thu Apr 12 2018
- [x] Thu May 10 2018
- [x] Thu Jun 07 2018
- [x] Thu Jul 12 2018
- [x] Thu Aug 09 2018
- [x] Thu Sep 13 2018
- [x] Thu Oct 11 2018
- [x] Thu Nov 08 2018
- [x] Thu Dec 13 2018

**Comment by lizafloyd** [comment]
This looks great @mandy6720 ! Let me offline with my co-organizers about scheduling and reach back out 👍

**Comment by elgreg** [comment]
Hi @mandy6720! I'm helping to wrangle our speaking schedule for the next few months. Are you still interested/able to present? Do any of these Thursdays work better or worse for you?

**Comment by mandy6720** [comment]
@elgreg I synced up with @lizafloyd over email - 4/12 still works for me :)

**Comment by elgreg** [comment]
Awesome!

**Comment by elgreg** [comment]
Great presentation! Thanks @mandy6720

**Comment by mandy6720** [comment]
Thanks @elgreg - it was a lot of fun :)
