### ISSUE TITLE
Talk Proposal

### ISSUE THREAD

**Issue by joellord** [dcjs/talks#47]
Your Name: Joel Lord
Your twitter handle: @joel__lord
A few words about yourself: Joel Lord is passionate about web and technology in general. In his spare time, Joel shares his findings via his blog Javascript Everything (http://www.javascripteverything.com).
He is currently a developer evangelist at Auth0, is a part-time teacher at the Algonquin College in programming and is involved in various developer communities of the Ottawa-Gatineau area.  In his free time, he works on his robots and automates some stuff around the house.
Star Wars.  All the way.

Talk title: I Don't Care About Security (And Neither Should You)
Talk abstract:  
Remember that time where setting up a login page was easy? It seems like nowadays, it take many weeks to start a project just to create a signup form, a login form and a forget password screen. And that is if you don’t need 2 factor authentication or passwordless authentication. During this presentation, the attendees will be introduced to OpenID and OAuth. They will also learn how to leverage this to create secure application or, most importantly, how to delegate to a third party so they can focus on their real work.
Expected length: 30-60 minutes
Available months: May.  I'll be in DC the 9 and 10 of May

_We meet on the second Thursday of the month generally. You can use this handy-dandy list to check dates:_

- [ ] Thu Jan 11 2018
- [ ] Thu Feb 08 2018
- [ ] Thu Mar 08 2018
- [ ] Thu Apr 12 2018
- [X] Thu May 10 2018
- [ ] Thu Jun 07 2018
- [ ] Thu Jul 12 2018
- [ ] Thu Aug 09 2018
- [ ] Thu Sep 13 2018
- [ ] Thu Oct 11 2018
- [ ] Thu Nov 08 2018
- [ ] Thu Dec 13 2018

**Comment by jakerella** [comment]
Hey Joel! Looks like you also talked to the NodeDC gang. That's great! If you plan to talk there I don't think it makes sense to also have you do DCJS - there's a fair amount of overlap. That said, DCJS would be happy to promote the talk!

**Comment by joellord** [comment]
Hi Jordan,
   fair enough.  The talk I give at NodeDC is a different one, more backend oriented but there is a bit of overlap in the content.  If you ever need a last minute speaker, I will be in town so just send me a message and I might be able to tweak the content to reduce redundancy.  

Thanks

**Comment by jakerella** [comment]
Thanks Joel! You can imagine if 50% of our audience just saw you speak last night it might be kind of weird. That said, if you don't find another speaking gig for the 10th you should come hang out with us at DCJS. ;)

**Comment by elgreg** [comment]
@joellord closing this for now. We plan to cross-promote your May 9 talk at our April meetup!
