### ISSUE TITLE
[HOLD] Painless end to end testing

### ISSUE THREAD

**Issue by Brantron** [dcjs/talks#48]
Your Name: Brandon Lawrence

  A few words about yourself: I’m a software engineer at Contactually. Co-organizer of [Nova Code and Coffee](https://www.meetup.com/NoVA-Code-Coffee/). I’m attracted to shiny js things and git questions

Talk title: The End to End tool you’ve always wanted actually exists. 

Talk abstract: I recently went to Assert.JS where I saw a demo for Cypress.io. I couldn’t believe this tool existed and I had never heard about it. I immediately realized all of the things I always wanted in e2e testing had already been done, including things I didn’t know I wanted. I’ll demo what a cypress workflow looks like and show the cool tricks I’ve learned to make testing easy.

 Expected length: 20-40 minutes

 Available months: March, April, May, Jun

- [X] Thu Apr 12 2018
- [X] Thu May 10 2018
- [X] Thu Jun 07 2018
- [ ] Thu Jul 12 2018
- [ ] Thu Aug 09 2018
- [ ] Thu Sep 13 2018
- [ ] Thu Oct 11 2018
- [ ] Thu Nov 08 2018
- [ ] Thu Dec 13 2018

**Comment by elgreg** [comment]
Sorry for not getting back to you sooner @Brantron! Any chance you'd be available to give this talk on Jun 14th?

**Comment by elgreg** [comment]
@Brantron We're putting together a short-talks session - think you can give the 15-20 minute version of this talk on Jun 14th?

**Comment by Brantron** [comment]
Yes!

**Comment by elgreg** [comment]
Great!

**Comment by elgreg** [comment]
@Brantron We're all set for tomorrow night! Looking forward to your talk!

**Comment by jakerella** [comment]
Hey @Brantron, heard about the new gig... best of luck! Will you still be in the DC area? Maybe we can have you at DCJS another time.

**Comment by jakerella** [comment]
Closing for now. :(
