### ISSUE TITLE
webpack like a boss

### ISSUE THREAD

**Issue by sjones6** [dcjs/talks#49]
Your Name: Spencer Jones
Your twitter handle: jones_spencera
A few words about yourself: I like to write JavaScript, contribute to open source, ride bikes, and drink coffee. I manage the Webpack setup for a large project with 100+ developers. 

Talk title: webpack like a boss 

... I'm happy with something less bombastic too :)

Talk abstract:  

webpack has extreme power but a steep learning curve. This is a 0-60 talk that will assume no prior knowledge but end with some advanced configurations. Learn how webpack works, how to integrate webpack into your project  ... and maybe we'll even write a custom plugin or loader on the fly. By the end of the talk, listeners should feel comfortable setting up webpack on their own (gasp!). This talk will focus on the newly released webpack 4.

Expected length: ~45mins

Available months: July and following

_We meet on the second Thursday of the month generally. You can use this handy-dandy list to check dates:_

- [X] Thu Jan 11 2018
- [ ] Thu Feb 08 2018
- [ ] Thu Mar 08 2018
- [ ] Thu Apr 12 2018
- [ ] Thu May 10 2018
- [ ] Thu Jun 07 2018
- [X] Thu Jul 12 2018
- [X] Thu Aug 09 2018
- [X] Thu Sep 13 2018
- [X] Thu Oct 11 2018
- [X] Thu Nov 08 2018
- [X] Thu Dec 13 2018

**Comment by elgreg** [comment]
I think this would be a great talk for July or August if you're available!

**Comment by sjones6** [comment]
Thanks! Let me confirm in a day or two. August is looking like the better option.

**Comment by jakerella** [comment]
Hey @sjones6, not sure if you saw but we rescheduled our lightning talks for August (which got cancelled due to a medical emergency). We have a potential for September, and possibly October (still sussing it out), but November is wide open, thoughts?

**Comment by jakerella** [comment]
ping!

**Comment by sjones6** [comment]
@jakerella : Thanks for ping! What's the date for October? I've got some travel in October, but could the 11th work on your end?. November is also looking pretty open for me.

**Comment by jakerella** [comment]
Yeah, October is the 11th... but I have someone tentatively set for that date. November 8 is open!

**Comment by sjones6** [comment]
ok, sign me up for Nov 8 then. If October 11th falls through, I could potentially move back with enough notice!

**Comment by jakerella** [comment]
Great! You've got November 8.

**Comment by sjones6** [comment]
Sweet! Confirmed.

**Comment by jakerella** [comment]
Hi! Soooo, my potential October 11 speaker can't do it, but could do November. Can you switch to October?

**Comment by sjones6** [comment]
Ay, sorry! I can't anymore :(

**Comment by jakerella** [comment]
No worries, thanks! We'll keep you on Nov 8

**Comment by jakerella** [comment]
Hi @sjones6! Are you still good for Nov 8? We'd like to get the meetup event posted this week.

**Comment by sjones6** [comment]
Still works for me! Thanks for confirming.

**Comment by sjones6** [comment]
Hey @jakerella I don't think I saw the announcement go out—just pinging here to make sure you don't need something from me!

**Comment by lizafloyd** [comment]
@sjones6 Thanks for double checking! We are still on and looking forward to your talk. The announcement just went out 👍

**Comment by sjones6** [comment]
Right on! Thanks!

**Comment by jakerella** [comment]
Hi there! Just making sure you're good to go for this week @sjones6.

**Comment by sjones6** [comment]
Yepper! See you on Thursday!

I've got slides and code so I'll bring a dongle for my mac machine to connect via HDMI. Should I bring anything else?

**Comment by jakerella** [comment]
I think that should be it!

**Comment by sjones6** [comment]
Right on. See you Thursday!
