### ISSUE TITLE
PWAs & Service Workers: Lessons from an Angular air quality app

### ISSUE THREAD

**Issue by jackkoppa** [dcjs/talks#54]
Your Name: Jack Koppa
Your twitter handle: [jackpkoppa](https://twitter.com/jackpkoppa)
A few words about yourself: I make things with a purpose. Love front-end development (currently modern Angular apps), clean technology, Chinese, & hiking/backpacking. Just moved to DC, after living most recently in Milwaukee & Shanghai.

Talk title: PWAs & Service Workers: Lessons from an Angular air quality app

Talk abstract:  
Progressive Web Apps (PWAs), and the functionalities that make them possible, continue to gain support across browsers. Most notably, Safari recently added support for key PWA features, esp. the [Service Workers](https://jakearchibald.github.io/isserviceworkerready/) used to enable offline functionality in a web application. There are things that are really great about PWAs, and things that are still really tough, and this talk will share a few lessons learned while working on Angular PWA: [cityaq](https://github.com/jackkoppa/cityaq), a simple "weather app for air quality". cityaq uses APIs from the DC open-source group [OpenAQ](https://github.com/openaq) to view, compare, and save air quality data across cities, and provides offline & native-like features. We'll discuss how those features were built leveraging the Angular [`service-worker`](https://angular.io/guide/service-worker-intro) package, how similar functionality can be created directly or with a generalized library like [Workbox](https://developers.google.com/web/tools/workbox/), and pitfalls to watch out for in the growing/changing world of PWAs.

Expected length: 15 minutes

Available months: August - November

- [x] DCJS[61] Thu Aug 09 2018 (preferred, as talk is lightning talk-length)
- [X] DCJS[62] Thu Sep 13 2018
- [X] DCJS[63] Thu Oct 11 2018
- [X] DCJS[64] Thu Nov 08 2018
- [ ] DCJS[65] Thu Dec 13 2018
- [ ] DCJS[66] Thu Jan 10 2019
- [ ] DCJS[67] Thu Feb 14 2019
- [ ] DCJS[68] Thu Mar 14 2019
- [ ] DCJS[69] Thu Apr 11 2019
- [ ] DCJS[70] Thu May 09 2019
- [ ] DCJS[71] Thu Jun 13 2019

**Comment by jakerella** [comment]
Thanks Jack! We'd love to see this at the Aug 9 lightning talks meetup. Let me know if you're good for that date!

**Comment by jackkoppa** [comment]
Yup, count me in for the 9th. Thanks!
