### ISSUE TITLE
[Lightning Talk] Describing data in APIs with JSON Schema

### ISSUE THREAD

**Issue by tfesenko** [dcjs/talks#56]
Your Name: Tanya Fesenko

Your Twitter Handle: tanya_fesenko

A few words about yourself: Lead software engineer with a proven track record of bringing products from concept to implementation. Background including working in four countries with people from almost all continents in corporate, semi-public and start-up environments. Driven, thorough, and passionate about technology.  

Talk title: Describing data in APIs with JSON Schema

Talk abstract: 
Data is in the center of many APIs used by developers. Which data format do these APIs accept? What we must include into the data payload and what are optional? How can we know which values this service accepts? What can I expect to receive in response? Can I automatically validate the data? JSON Schema is the answer to these questions. It is a precise description of JSON data which is both machine-readable and human-friendly. In this presentation, I will talk about how JSON schema is used to describe payload in OpenAPI specification and provide an overview of my favorite features. By the end of this talk, you will know how to describe objects and their properties, what is required in the request, and what will be returned in a response. In addition to this,  you will also know how to model data type inheritance in JSON Schema.  

Expected length: 10-15 mins
Available months: August - October 2018

- [x] DCJS[61] Thu Aug 09 2018
- [x] DCJS[62] Thu Sep 13 2018
- [x] DCJS[63] Thu Oct 11 2018
- [ ] DCJS[64] Thu Nov 08 2018
- [ ] DCJS[65] Thu Dec 13 2018
- [ ] DCJS[66] Thu Jan 10 2019
- [ ] DCJS[67] Thu Feb 14 2019
- [ ] DCJS[68] Thu Mar 14 2019
- [ ] DCJS[69] Thu Apr 11 2019
- [ ] DCJS[70] Thu May 09 2019
- [ ] DCJS[71] Thu Jun 13 2019

**Comment by jakerella** [comment]
Hey Tanya! I'm not sure if my reply to meetup made it to you or not, I was on vacation and without a laptop. Did you come to the meetup last week? If not, we can try to work this in before another talk later in the year. Let me know!

**Comment by tfesenko** [comment]
Hi @jakerella, I hoped you enjoyed your vacation! 
> Did you come to the meetup last week? If not, we can try to work this in before another talk later in the year. Let me know!

I didn't present last week.  And I would be happy to present before another talk -- meetups in September or October are the most convenient for me.

**Comment by jakerella** [comment]
Sounds good... lemme think about which one would be best, right now I'm leaning toward September 13.

**Comment by jakerella** [comment]
Hey Tanya! So for the long silence. Any chance you'd be up for doing this talk in February or March? I'm thinking that I'll try to schedule two shorter talks together. So we'd give you a 20-ish minute slot, and someone else the same... thoughts?

Alternatively, if you think this talk could be expanded into more like 40 minutes (with some examples, case studies/use cases/etc) then we'd love to have you on in early 2019 solo. Let me know!

**Comment by jakerella** [comment]
Hi Tanya, looks like you may not check GitHub too often? I'll ping you on twitter, but wondering if you'd be up for doing this short talk in May and we can line up another short talk and have a 2-talk night. Thoughts?

**Comment by tfesenko** [comment]
Hi @jakerella, I just moved to Boston and won't be able to present in May because I won't be in DC. 
But thank you for considering my talk!

**Comment by jakerella** [comment]
Ah... sad. But ok, thank you! Good luck up there!

**Comment by jackkoppa** [comment]
Hey @jakerella - I had asked about a pretty similar topic over in @dctech

https://github.com/dctech/speaking/issues/45

Was still looking to see if someone had frontend experience with JSON Schema, but I'd be super interested in the topic regardless

**Comment by jakerella** [comment]
Cool... I'll post over there that DCJS would love to see this
