### ISSUE TITLE
[Lightning Talk] Operation Code DC: Helping the military community code the future the in nation's capital.

### ISSUE THREAD

**Issue by bushidocodes** [dcjs/talks#57]
Your Name: Sean McBride
Your twitter handle: bushidocodes
A few words about yourself: I'm an Army veteran currently working as a fullstack software developer at Decipher Tech Studios. In my spare time, I volunteer with Operation Code to mentor veterans and military spouses seeking to transition into software development.

Talk title: Operation Code DC: Helping the military community code the future the in nation's capital.

Talk abstract:  
I want to give a brief introduction to how Operation Code helps the veteran and milspouse communities and discuss a few success stories. 

Expected length: 5mins

Available months: All of them. Ideally hoping to speak this Thursday, August 9th at the event focused on Lightning talks!

**Comment by jakerella** [comment]
Thanks Sean!
