### ISSUE TITLE
Cleaning up Code with Async/Await

### ISSUE THREAD

**Issue by froi** [dcjs/talks#58]
Your Name: Froilan Irizarry
Your twitter handle: skfroi
A few words about yourself: I'm the backend engineer at Code.gov. My career spans both the private and government sectors. Before Code.gov I was part of the USDS working with CMS to bring the QPP program to life.

Talk title: Cleaning up Code with Async/Await

Talk abstract:  
Inheriting a project can sometimes be a hassle. Multiple iterations on a code base by different people can leave a ton of cruft. When dealing with asynchronous code you sometimes end up with a mix of callbacks and Promise chains. What to do to fix this? Start using async/await!

Expected length: five to ten minutes

Available months: [Example: July, Aug, Sept | Example: Not October | Example: All of them]

_We meet on the second Thursday of the month generally. You can use this handy-dandy list to check dates:_

- [x] DCJS[61] Thu Aug 09 2018
- [ ] DCJS[62] Thu Sep 13 2018
- [ ] DCJS[63] Thu Oct 11 2018
- [ ] DCJS[64] Thu Nov 08 2018
- [ ] DCJS[65] Thu Dec 13 2018
- [ ] DCJS[66] Thu Jan 10 2019
- [ ] DCJS[67] Thu Feb 14 2019
- [ ] DCJS[68] Thu Mar 14 2019
- [ ] DCJS[69] Thu Apr 11 2019
- [ ] DCJS[70] Thu May 09 2019
- [ ] DCJS[71] Thu Jun 13 2019

**Comment by jakerella** [comment]
Thanks Froi!
