### ISSUE TITLE
Kick Those Scripts to the Sandbox

### ISSUE THREAD

**Issue by adunkman** [dcjs/talks#59]
Your Name: Andrew Dunkman
Your twitter handle: @adunkman
A few words about yourself: Hi friends! I’ve been hacking on Twitter’s embed script recently, and I’m thinking about presenting a talk about it. It might not come together, but I’ll give it a shot! 

### Kick Those Scripts to the Sandbox

Do you want Tweets or your latest Instagram food picture to display nicely in your site? Just load this third-party script into your site — never mind what it does! … err, what’s the difference between third-party scripts and a cross-site scripting attack again? Can’t third-party scripts steal user credentials, track users without their consent, and hijack your site for advertising purposes? In this talk, we’ll discuss different ways of sandboxing these scripts to increase your site’s security, stability, and protect the privacy of your users. You’ll leave with an understanding of the latest browser features designed to protect you and your users.

Expected length: 30–45 minutes (can adjust to either, depending on what you prefer).

Available dates: 

- [x] DCJS[62] Thu Sep 13 2018
- [x] DCJS[63] Thu Oct 11 2018
- [x] DCJS[65] Thu Dec 13 2018

**Comment by jakerella** [comment]
This sounds great! I'm trying to lock down a few months of speakers and have reached out to a number of folks. How about we tentatively jot you down for December, and if I strike out for October I'll let you know?

**Comment by adunkman** [comment]
Sounds good @jakerella! I can bump to next year too — I’m not picky. 😄

**Comment by jakerella** [comment]
Okay, I've got you down for December 2020. ;)

KIDDING! We'll figure it out.

**Comment by jakerella** [comment]
Hola! Any chance you're up for doing this talk January 10th?

**Comment by adunkman** [comment]
Howdy! Unfortunately I can’t make that date — I’ll be at [Codemash](http://www.codemash.org/). 

Feb 14 is Valentine’s Day… so I’ll have to get special approval if that’s the date of the next one. 😉

**Comment by jakerella** [comment]
:) No worries, thanks!

**Comment by jakerella** [comment]
Hey! Sooo... March or April?

**Comment by jakerella** [comment]
ping! Any chance you're available March 14 or April 11?

**Comment by adunkman** [comment]
Howdy! Was out exploring Austin and New Orleans. 😄 

I think April 11th works — March 14 is my anniversary (π day). Confirming with work (I’m not sure what I have to do formally now that I’m a govvie) before formally accepting, but I don’t imagine anything will come up.

**Comment by adunkman** [comment]
Confirmed! April 11th works for me.

**Comment by jakerella** [comment]
w00t! Thanks, we're doing meetup announcements shortly after the previous month's meetup, so you won't see it live until after March 14.

**Comment by jakerella** [comment]
Thanks Andy!

**Comment by adunkman** [comment]
Slides for reference later: https://speakerdeck.com/adunkman/kick-those-scripts-to-the-sandbox-at-dc-javascript
