### ISSUE TITLE
Building a process finder in Node.js

### ISSUE THREAD

**Issue by corsoa** [dcjs/talks#60]
Your Name: Aaron Corso
Your twitter handle: @corsoa
A few words about yourself: I’m a software engineer focused on building SaaS products for the higher education sector. I started building websites because I wanted to post a picture of my cat and never got tired of trying to make a better way to share cat pictures.

Talk title: Building a process finder in Node.js

Talk abstract:
This talk will examine my journey to build a cross-OS mechanism to find relevant process information like bound ports, directories, and command line arguments, and how I solved these compatibility issues with Node.js to produce a program that is easy for beginners to the command line. I will be showing code samples of how the program works on Linux, and explain how you can construct a basic command line tool using yargs and cli-table2 for formatting.
Some basic command line knowledge is preferred, but will be explained.

Expected length: 10 minutes

Available months: All of them.

_We meet on the second Thursday of the month generally. You can use this handy-dandy list to check dates:_

- [ ] DCJS[61] Thu Aug 09 2018
- [x] DCJS[62] Thu Sep 13 2018
- [x] DCJS[63] Thu Oct 11 2018
- [x] DCJS[64] Thu Nov 08 2018
- [x] DCJS[65] Thu Dec 13 2018
- [ ] DCJS[66] Thu Jan 10 2019
- [ ] DCJS[67] Thu Feb 14 2019
- [ ] DCJS[68] Thu Mar 14 2019
- [ ] DCJS[69] Thu Apr 11 2019
- [ ] DCJS[70] Thu May 09 2019
- [ ] DCJS[71] Thu Jun 13 2019

**Comment by jakerella** [comment]
Hi Aaron! Sorry for the silence, we just had a backlog of talks to get through. Any chance you want to do this on May 9 along with a few other short talks?

**Comment by corsoa** [comment]
@jakerella Sure, that works for me.

**Comment by jakerella** [comment]
Great, thanks!

**Comment by jakerella** [comment]
Hey Aaron! Just checking in to make sure you have everything you need for Thursday. Let me know if there is anything I can help with! And thanks for RSVPing on meetup!
