### ISSUE TITLE
NativeScript

### ISSUE THREAD

**Issue by dbarbour** [dcjs/talks#61]
Your Name: Dwight Barbour

I'm a web-database developer and IT consultant.  LatelyI dabble in mobile tech stacks, solve business issues, and coach new IT consultants.

For over 15 years I have design and teaching experience for building a skilled IT workforce.  Currently building curriculum for a school based on predominantly JavaScript/ECMAscript as the language of choice.

Talk title: "Intro to NativeScript Cross-platform Mobile Tech Stack -why? what? how?"

Talk abstract:  
Learn how JavaScript/ECMAscript is not just for the web!  Compare tech stacks for using JS for mobile apps.  Explore NativeScript's ecosystem and their free IDE.

This is an introductory talk exploring JS to create native cross-platform (iOS, Android) native apps. 
 Topics include:
(1) native vs hybrid vs cross-platform native tech stacks 
(2) move from web to mobile dev: you already have the skills
(3) explore NativeScript's free, in-browser IDE. 
(4) (optional) Hands-on exercising tweaking code samples

Expected length: 30min - 90min extremely flexible.
Of course if we include hands-on exercises, the time required would increase or content depth would decrease.

Available months: All months good!  Available most Thursdays!

- [X] DCJS[64] Thu Nov 08 2018
- [X] DCJS[65] Thu Dec 13 2018
- [X] DCJS[66] Thu Jan 10 2019
- [X] DCJS[67] Thu Feb 14 2019
- [X] DCJS[68] Thu Mar 14 2019
- [X] DCJS[69] Thu Apr 11 2019
- [X] DCJS[70] Thu May 09 2019
- [X] DCJS[71] Thu Jun 13 2019

**Comment by jakerella** [comment]
Hi @dbarbour! Would you be able to do this talk in February? It would be February 14.

**Comment by dbarbour** [comment]
Regarding the NativeScript talk
(https://github.com/dcjs/talks/issues/61), February sounds great.
Do you have a location?  About how many people do you expect?   I might
have a location near 20th and L that can be used.
Thanks, Jordan and Happy New Year!

Dwight.


On Tue, Jan 1, 2019, at 12:55 PM, Jordan Kasper wrote:
> Hi @dbarbour[1]! Would you be able to do this talk in February? It
> would be February 14.> — You are receiving this because you were mentioned. Reply to this
> email directly, view it on GitHub[2], or mute the thread[3].

Links:

  1. https://github.com/dbarbour
  2. https://github.com/dcjs/talks/issues/61#issuecomment-450746547

**Comment by jakerella** [comment]
Yeah, we have a location. We're currently hosted at the CHIEF offices just off Dupont Circle. Our attendance ranges from 30 to 60, depending on the month. My guess is that with Feb 14 being Valentine's Day it'll be a lighter crowd. We like to keep our talks under an hour to keep people's attention. It would be great if you could update the talk abstract to be a bit more narrative, in paragraph form.

I'll go ahead and pencil you in for now! Thanks!

**Comment by jakerella** [comment]
Hi Dwight! The meetup event for February is live. Don't forget to RSVP! We'll check in again once it gets closer, but let me know if you have any questions!

https://www.meetup.com/DC-JavaScript/events/258254136/

**Comment by jakerella** [comment]
Hi Dwight! The meetup is coming up this Thursday! Is there anything you need to be ready?

Please be sure to RSVP on meetup.com!!
https://www.meetup.com/DC-JavaScript/events/258254136/

**Comment by dbarbour** [comment]
My apologies for the late response.  I'll need internet and a way to
project slides.  Nothing out of the ordinary.  :)
Thank you!


--
  Dwight H. Barbour
  Database, Web, & Mobile Engineer
  Consultant and Instructor



On Sun, Feb 10, 2019, at 10:25 AM, Jordan Kasper wrote:
> Hi Dwight! The meetup is coming up this Thursday! Is there anything
> you need to be ready?> Please be sure to RSVP on meetup.com!!
> https://www.meetup.com/DC-JavaScript/events/258254136/


> — You are receiving this because you were mentioned. Reply to this
> email directly, view it on GitHub[1], or mute the thread[2].

Links:

  1. https://github.com/dcjs/talks/issues/61#issuecomment-462141668

**Comment by jakerella** [comment]
Hey Dwight! Are you slides posted anywhere that we can link to?
