### ISSUE TITLE
Shared Component Libraries

### ISSUE THREAD

**Issue by jackkoppa** [dcjs/talks#62]
**Your Name:** Jack Koppa  
**Your twitter handle:** [@jackpkoppa](https://twitter.com/jackpkoppa)
**A few words about yourself:** Jack Koppa is a front-end developer, focused on modern web apps & best practices for maintainable, collaborative code. He especially enjoys Vue.js & TypeScript in his work @ POLITICO; passionate about public policy, clean technology, hiking/backpacking, and Chinese.

**Talk title:** Shared Component Libraries: Challenges, Tips, Storybook

**Talk abstract:**  
For any company with multiple web applications, the idea of shared components begins to become immensely tempting. This goal comes with significant challenges: separate development environments, bundling components for consumption, versioning across projects, to name a few. The benefits, however, can be immense: DRY code, brand & experience consistency across products, and encouraged communication across teams. Need a dropdown, or a table, or a search bar? Let’s not only save time whenever it's used; let’s make sure it looks **and** works the same across products.

To help us reap the rewards of shared component libraries while minimizing the hazards, we’ll use Storybook to give us a dedicated development & testing environment for our shared components, including an intuitive interface for non-devs to interact with & improve our library. We'll do a minor dive into NPM publishing: how easy it is to publish your first package (even to @scope it for your company), and how complex it can become to handle versioning + local testing (with recommendations to make it less so). We'll look at how Vue specifically has addressed the question of exporting compiled components, an overview of React & Angular approaches, and the possibility of using plain Web Components for modern projects. Finally, some bonus notes, on lessons learned at POLITICO & potential tricks to try out - TypeScript for self-documenting components, anyone?

**Expected length:** 45-60 minutes

**Available months:** Dec, Jan, Feb, Apr (likely May & June, but unsure this far out)

_We meet on the second Thursday of the month generally. You can use this handy-dandy list to check dates:_

- [x] DCJS[65] Thu Dec 13 2018
- [x] DCJS[66] Thu Jan 10 2019
- [x] DCJS[67] Thu Feb 14 2019
- [ ] DCJS[68] Thu Mar 14 2019
- [x] DCJS[69] Thu Apr 11 2019
- [ ] DCJS[70] Thu May 09 2019
- [ ] DCJS[71] Thu Jun 13 2019

**Comment by jakerella** [comment]
Hey Jack! Would you be up for doing this talk June 13 or July 11? (I'm hitting a few people up, so I may shift around depending on who responds. ;) )

**Comment by jackkoppa** [comment]
Hey @jakerella - yup, either would work, June slightly better.

**Comment by jakerella** [comment]
Great, let's plan on you speaking June 13 then!
