### ISSUE TITLE
 Linting your XSS troubles away

### ISSUE THREAD

**Issue by oliikit** [dcjs/talks#64]
**Your Name:** Olivia Brundage
**Your twitter handle:** [@oliikit](https://twitter.com/oliikit/)  
**A few words about yourself:** I'm a Security Engineer at Mapbox where I secure and maintain availability on our cloud infrastructure. I write mostly JavaScript these days, a big videogame nerd, and have two adorable cats. 🤓 (And of course, Star Trek > Star Wars. 💥)

**Talk title:** Linting your XSS troubles away

**Talk abstract:**  
[Cross-site scripting (XSS)](https://www.owasp.org/index.php/Cross-site_Scripting_(XSS)) is one of the most popular, and potentially most damaging, client-side attack vector - and it's one of the easiest to prevent. XSS happens because data isn't properly validated and sanitized. As it turns out, especially with JavaScript, the correct design pattern in handling any sort of data can be checked to prevent XSS attacks.
Within this talk, you will see various demos of XSS attacks (like [DOM-based](https://www.owasp.org/index.php/DOM_based_XSS_Prevention_Cheat_Sheet) and [reflected](https://www.owasp.org/index.php/Cross-site_Scripting_(XSS)#Stored_and_Reflected_XSS_Attacks)) and be introduced to tools that can help you combat and prevent this vulnerability from happening through the use of an [eslint plugin](https://github.com/Rantanen/eslint-plugin-xss). Don't use eslint plugin? That's fine! We'll go over different tools that do the job.
I will demonstrate how we've implemented this tool into our code pipeline at Mapbox, so that you can be confident, like us, in deploying XSS free code.

**Expected length:** 20-40 minutes; rather flexible on time frame.

**Available months:**

_We meet on the second Thursday of the month generally. You can use this handy-dandy list to check dates:_

- [x] DCJS[65] Thu Dec 13 2018
- [x] DCJS[66] Thu Jan 10 2019
- [ ] DCJS[67] Thu Feb 14 2019
- [ ] DCJS[68] Thu Mar 14 2019
- [ ] DCJS[69] Thu Apr 11 2019
- [ ] DCJS[70] Thu May 09 2019
- [ ] DCJS[71] Thu Jun 13 2019

**Comment by jakerella** [comment]
Thanks @oliikit! We'll get the meetup event posted for December 13 up after this week's meetup. Looking forward to it!

**Comment by adunkman** [comment]
This talk looks really cool. 🙂

**Comment by jakerella** [comment]
Hey @oliikit! Are you set for Thursday? I won't actually be in town sadly, but @elgreg, @asabaylus, and @lizafloyd will be there (or, at least 2 of them ;) ).

Also, please be sure to register for the event (and spread the word)!
https://www.meetup.com/DC-JavaScript/events/256721171/

**Comment by asabaylus** [comment]
If you need anything just ping us.

Asa

**Comment by oliikit** [comment]
Thank you, @asabaylus and @jakerella! I should be all good to go. 🤗

**Comment by robbiethegeek** [comment]
Was a super successful talk
