### ISSUE TITLE
Effective Javascript Testing

### ISSUE THREAD

**Issue by freestylebit** [dcjs/talks#65]
**Your Name:** Peter Cho
**Your twitter handle:** freestylebit
**A few words about yourself:** Prefers Ledo's over Papa John's, can sprint a minute sprint in 60 seconds, does not agree that hot dogs are sandwiches.

**Talk title:** Effective Javascript Testing

**Talk abstract:**  
A persuasive dialogue on effective testing methodologies and things to look out for when building out your suite.  Talk is meant to be technology agnostic and I will try to not make it framework-specific (e.g. react, angular), but examples may use popular frameworks (e.g. jest, mocha) for demonstration purposes.  Topics (and opinions) may include:

- Implementation detail: Is it worth writing tests to verify the internals?
- Code Coverage: Fallacy or a quantitative metric?
- Different types of tests and why they all have their place in the testing ecosystem
- How much testing is enough, and what will give you the most bang for your buck
- Why you should use open source third party dependencies more often
- How strong type checking can save you a lot of work

**Expected length:**  45 minutes

**Available months:** 

- [] DCJS[65] Thu Dec 13 2018
- [X] DCJS[66] Thu Jan 10 2019
- [X] DCJS[67] Thu Feb 14 2019
- [X] DCJS[68] Thu Mar 14 2019
- [X] DCJS[69] Thu Apr 11 2019
- [ ] DCJS[70] Thu May 09 2019
- [X] DCJS[71] Thu Jun 13 2019

**Comment by jakerella** [comment]
Thanks Peter! Trying to figure out early 2019 now with previous submissions. I think we could get to this one early to mid Spring... but if everyone bails on me for Feb/Mar/Apr then I might ping you. ;)

**Comment by freestylebit** [comment]
No problem.  I figured the backlog is large as it is, but let me know a few weeks in advance so I can finalize the slides.

**Comment by jakerella** [comment]
Hey there! What do you think about July 13 or August 8?

**Comment by freestylebit** [comment]
July and August is relatively wide open.  For July, are we talking about July 18?

**Comment by jakerella** [comment]
Oops, nope... July 11. Thoughts?

**Comment by freestylebit** [comment]
As far as I know, either dates looks good!

**Comment by jakerella** [comment]
Looks like Jack Koppa got June... so how about July 11?

**Comment by freestylebit** [comment]
Yea that should work.  I'll start reviewing my slides again in a few weeks!

**Comment by jakerella** [comment]
Nice! THANKS!!

**Comment by jakerella** [comment]
Hey @freestylebit! Are you ready for July 11? We'll probably get the meetup event published this week, let me know if there's anything you need.

**Comment by freestylebit** [comment]
I should be ready.  I'll get the slides finalized in a week!

**Comment by freestylebit** [comment]
The meetup can also be renamed to "Testing for Value", too (if it's not too late).
