### ISSUE TITLE
⚡️console.ident - your new best debugging friend⚡️ 

### ISSUE THREAD

**Issue by easilyBaffled** [dcjs/talks#66]
Your Name: Danny Michaelis
Your twitter handle: @easilyBaffled
A few words about yourself: A hobbyist game developer trying to bend JS 

Talk title: ⚡️console.ident - your new best debugging friend⚡️

Talk abstract:
A cleaner logging function that takes advantage of expressive Javascript.
```js
console.ident = x => ( console.log( x ), x )
```
*And Possible trojan horse for a longer talk on ASTs*

Expected length: 5-8

Available months: All of them

We meet on the second Thursday of the month generally. You can use this handy-dandy list to check dates:

- [x] DCJS[65] Thu Dec 13 2018
- [x]  DCJS[66] Thu Jan 10 2019
- [x]  DCJS[67] Thu Feb 14 2019
- [x]  DCJS[68] Thu Mar 14 2019
- [x]  DCJS[69] Thu Apr 11 2019
- [x]  DCJS[70] Thu May 09 2019
- [x]  DCJS[71] Thu Jun 13 2019

**Comment by jakerella** [comment]
Thanks Danny! I just sent a message on your other submission as well. We'll find a good month in the spring for lightning talks and keep this one in the hopper. Alternatively, I might find an opening for two small talks on the same night (but not a full lightning talk night).

**Comment by jakerella** [comment]
Hey Danny! Any chance you want to do this May 9? I'm thinking about getting a few small talks together for that evening.

**Comment by easilyBaffled** [comment]
Yup, that would be great.

**Comment by jakerella** [comment]
Cool, jotting you down for it.

**Comment by jakerella** [comment]
Hey Danny! Just checking to make sure you're ready for Thursday. Let me know if there is anything I can do to help!

Also, please be sure to RSVP on the meetup page!
https://www.meetup.com/DC-JavaScript/events/260787672

**Comment by easilyBaffled** [comment]
Yup, I'm ready.
