### ISSUE TITLE
NPM Scripts as a build process

### ISSUE THREAD

**Issue by internette** [dcjs/talks#67]
**Your Name:**  [Antoinette Janus](https://acjanus.co)  
**Your twitter handle:** [@twaffles](https://twitter.com/twaffles)  
**A few words about yourself:** Runs CodePenDC, avid coffee consumer, and fried chicken over everything minus dogs.

**Talk title:** NPM Scripts as a build tool

**Talk abstract:**  
Webpack is great, but learning is a time intensive process. The more intensive development becomes, the easier our build processes should be. Currently this isn't the case. But build processes don't have to be insane. Enter NPM Scripts. We'll talk about what NPM Scripts are, how to incorporate them into your build system, and how to clean your webpack configs. You may learn that you may not need webpack at all.

**Expected length:** 30-45 minutes

**Available months:** Anytime before June

_We meet on the second Thursday of the month generally. You can use this handy-dandy list to check dates:_

- [ X ] DCJS[67] Thu Feb 14 2019
- [ X ] DCJS[68] Thu Mar 14 2019
- [ X ] DCJS[69] Thu Apr 11 2019
- [ X ] DCJS[70] Thu May 09 2019

**Comment by jakerella** [comment]
Sounds great! We have March 14 available if you're interested?

**Comment by internette** [comment]
@jakerella March 14 is perfect!

**Comment by lizafloyd** [comment]
@internette Thanks so much for speaking! You are scheduled and our event is posted here https://www.meetup.com/DC-JavaScript/events/258975279/ .  Looking forward to seeing you there!

**Comment by jakerella** [comment]
Hi again @internette! We wanted to make sure you have everything you need for this week's meetup. There will be a laptop stand, screen, projector, mic, and various connectors (although you should try to have your own video connectors just in case).

Also, I didn't see your name on the RSVP list for the meetup, can you be sure to RSVP? This is mostly for building security: https://www.meetup.com/DC-JavaScript/events/258975279
