### ISSUE TITLE
Participate in joint DC Tech speaking repo?

### ISSUE THREAD

**Issue by adunkman** [dcjs/talks#68]
It’d be cool to participate in this: https://github.com/dctech/speaking. 

It’s a new thing, will be [publicized on Monday, Jan 21](https://github.com/dctech/speaking/issues/4).

It wouldn’t necessarily replace this repo, but it’d require the organizers here to watch that repo to see if talks came up that y’all’d be interested in giving. 

Thumbs/comments/thoughts?

**Comment by jakerella** [comment]
I'll get a PR out shortly!

**Comment by jakerella** [comment]
https://github.com/dctech/speaking/pull/5
