### ISSUE TITLE
Up and Running with AWS Amplify

### ISSUE THREAD

**Issue by kkemple** [dcjs/talks#69]
**Your Name:** Kurtis Kemple  
**Your twitter handle:** `@kurtiskemple`
**A few words about yourself:** I'm a senior developer advocate with AWS. I've been a fullstack dev for a few years now. I love to meet new folks and recently moved to VA Beach. Figured I would get involved in the DC tech community. Star Wars > Star Trek (but not by much, like them both). Love to longboard and hate winter.

**Talk title:** Up and Running with AWS Amplify

**Talk abstract:**  
When it comes time to take your product to production you are suddenly faced with a lot of issues. Can we scale our user base? Do we have enough data storage? How will we handle proper authorization? How will we host? In this talk I will live code an app that can scale from 1 to 1,000,000 users without having to change a single line of code. How you ask? By taking advantage of the AWS Amplify toolchain. Amplify allows front-end developers like you and me to quickly and easily spin up back-end infrastructure, data bases, and user management without having to leave our terminal. By building on top of this toolchain you get to focus solely on what matters. Building your next project.

**Expected length:** 30-45min

**Available months:** May, Jun, July, Aug, Sept

_We meet on the second Thursday of the month generally. You can use this handy-dandy list to check dates:_

- [ ] DCJS[65] Thu Dec 13 2018
- [ ] DCJS[66] Thu Jan 10 2019
- [ ] DCJS[67] Thu Feb 14 2019
- [ ] DCJS[68] Thu Mar 14 2019
- [ ] DCJS[69] Thu Apr 11 2019
- [x] DCJS[70] Thu May 09 2019
- [x] DCJS[71] Thu Jun 13 2019

**Comment by kkemple** [comment]
Is there anything else I need to do here?

**Comment by jakerella** [comment]
Hi @kkemple! Sorry for the delay, speaker wrangling is my job, but I've been traveling a ton lately. I think that toolchain looks really interesting, but I have to say that the talk submission looks like a product marketing talk (even if it is all demo and hands-on). We tend to shy away from talks that simply promote a particular product. I'm open to suggestions on how to alter the talk to make it less so... feel free to reach out!

**Comment by kkemple** [comment]
Yeah, that's perfectly fine with me. I have a talk on Improving UX with AI I could give, it uses Amplify but it's not the focus of the talk. The talk is really about how to design/developer with AI in mind.
