### ISSUE TITLE
React hooks

### ISSUE THREAD

**Issue by mcrowder65** [dcjs/talks#71]
**Your Name:** Matt Crowder
**Your twitter handle:** https://twitter.com/mcrowder65
**A few words about yourself:** Northern Virginia native, passionate javascript developer, I also enjoy the finer things in life including, but not limited to: little caesars pretzel crust pizza.

**Talk title:**  React Hooks

**Talk abstract:**  
First, we'll learn about higher-order-components, and talk about how they're good, and why they're bad.

Then, we'll learn about render props, and talk about how they're good, and why they can end up being bad (in some cases).

Then, we'll learn how to convert "bad" render props/hoc's into easy to read, good code written with hooks.

Then we'll specifically learn about useState, when to use useReducer instead of useState.

Then we'll take a look at a class equivalent useEffect example, then, refactor that using useEffect.

And lastly, we'll learn when/how to use useMemo and useCallback.

**Expected length:** 45 minutes is fine, I gave this talk at NoVa.JS and it took around 50 minutes.

**Available months:** [Example: July, Aug, Sept | Example: Not October | Example: All of them]

_We meet on the second Thursday of the month generally. You can use this handy-dandy list to check dates:_

- [X] DCJS[70] Thu May 09 2019
- [X] DCJS[71] Thu Jun 13 2019

**Comment by jakerella** [comment]
Hi Matt! Not sure if you saw, but @tommymarshall submitted basically the same thing a few weeks ago. :)

We're open to a joint meetup, but we'd probably only be able to do one talk on this topic for now.

**Comment by mcrowder65** [comment]
hey 👋 @jakerella, I'm happy to just submit another topic, stay tuned :)

**Comment by jakerella** [comment]
Thanks! Can I close this one up?

**Comment by mcrowder65** [comment]
Sure go ahead, thanks
