### ISSUE TITLE
React-testing-library

### ISSUE THREAD

**Issue by mcrowder65** [dcjs/talks#72]
**Your Name:** Matt Crowder
**Your twitter handle:** https://twitter.com/mcrowder65
**A few words about yourself:** Northern Virginia native, passionate javascript developer, I also enjoy the finer things in life including, but not limited to: little caesars pretzel crust pizza.

**Talk title:**  react-testing-library

**Talk abstract:**  If you had to rewrite your tests when writing a hook in your React application, then you're writing tests wrong.

[react-testing-library](https://github.com/kentcdodds/react-testing-library) is what it sounds like, but more importantly, it encourages writing tests in the way that your end users will be using your components.

In this talk, I will first introduce react-testing-library, what it is, what it encourages, and what it does best. I'll then dive into how to effectively test a react component, first a smaller component, then a "larger" component with redux, i18n dependencies, etc., then I will show all of the different APIs that react-testing-library provides, and how to effectively use them. Then, I'll show how to write effective tests across an entire application (writing reusable, effective tests that are not brittle).

**Expected length:** 45 minutes is fine

**Available months:** [Example: July, Aug, Sept | Example: Not October | Example: All of them]

_We meet on the second Thursday of the month generally. You can use this handy-dandy list to check dates:_

- [X] DCJS[70] Thu May 09 2019
- [X] DCJS[71] Thu Jun 13 2019
- I can basically speak anytime May and onwards.

**Comment by lizafloyd** [comment]
Hi @mcrowder65 ! I wanted to reach out to see if you're still interested in giving this talk? If so I'd like to try to get you on the schedule! Thanks for your interest in DCJS.

**Comment by mcrowder65** [comment]
Hey Liza! Thanks for reaching out! I am actually giving this talk at nationjs in December. So I don’t think I’d be interested in giving it in the near future, I think I’d prefer maybe March at the earliest next year? But I’m not sure how far booked y’all are. Thanks!

**Comment by jakerella** [comment]
Hey Matt, we'll hold off on this until the Spring, but we'll hit you up then. ;)

**Comment by jakerella** [comment]
Hey Matt! Any chance you could do this talk in April? It would be April 9. Let me know!

**Comment by mcrowder65** [comment]
Hey Jordan, I think I'm gonna go ahead and not give this talk, I haven't given it in a while and I don't think I want to give it anymore, sorry!

**Comment by jakerella** [comment]
No worries, thanks for the update!
