### ISSUE TITLE
Human Readable JavaScript

### ISSUE THREAD

**Issue by laurieontech** [dcjs/talks#74]
**Your Name:** Laurie Barth
**Your twitter handle:**@laurieontech
**A few words about yourself:** Laurie is a software developer, conference speaker and frequent blogger. During normal business hours she is a consultant at Ten Mile Square. Depending on the day she can be found using any number of technologies from different languages to frameworks and other support tools. When she isn't writing code you can find her playing board games and eating cupcakes.

**Talk title:** Human Readable JavaScript: Using ES2015+ to Craft Better Code

**Talk abstract:**  
Love JavaScript? Awesome! Hate JavaScript? That's ok! We know that JavaScript hasn't been very easy to read in the past, lots of dollar signs and slick one-liners. 
The good news is that things have gotten better! In this talk we'll look at some of the syntax ES2015+ introduced to help us write more readable code for our coworkers and our future selves.

**Expected length:** 45 min

**Available months:** August and beyond

_We meet on the second Thursday of the month generally. You can use this handy-dandy list to check dates:_

- [ ] DCJS[65] Thu Dec 13 2018
- [ ] DCJS[66] Thu Jan 10 2019
- [ ] DCJS[67] Thu Feb 14 2019
- [ ] DCJS[68] Thu Mar 14 2019
- [ ] DCJS[69] Thu Apr 11 2019
- [ ] DCJS[70] Thu May 09 2019
- [ ] DCJS[71] Thu Jun 13 2019

**Comment by jakerella** [comment]
Hey Laurie! Thanks for submitting this one. I'm going to tentatively put you down for September. As I mentioned on Twitter, I might ping you about August if that's possible.

**Comment by laurieontech** [comment]
Sounds like a plan!

**Comment by jakerella** [comment]
Hey Laurie! We chatted on Twitter about this, but just confirming that you are good to go on August 8 for this talk?

**Comment by laurieontech** [comment]
Yup! Ok my calendar

-Laurie
