### ISSUE TITLE
Hasura GraphQL Engine

### ISSUE THREAD

**Issue by ksteigerwald** [dcjs/talks#75]
**Your Name:** Kris Steigerwald 
**Your twitter handle:** ksteigerwald  
**A few words about yourself:** Software Engineer that enjoys musing over Javascript, Swift and product development in general. 

**Talk title:** Hasura a Realtime GraphQL Engine

**Talk abstract:**  
Interested in GraphQL but don’t have the time to learn it? Hasura might be for you then. Even if you know GraphQL and are looking for ways to lessen the tedium of building postgres backed API's - Hasura has a lot to offer. 

Kris Steigerwald, Sr Software Engineer with Capital One will be presenting on building three factor applications with Hasura an instant realtime GraphQL Engine. During this meetup we will do an overview of GraphQL and then learn about the many features that Hasura offers such as; powerful queries out of the box, real time subscriptions and remote schemas. Kris will also showcase some products he has built using Hasura and share with you his experience. 

**Expected length:** Less than 30 minutes, but I can make it longer/shorter if needed. 

**Available months:** All of them.

_We meet on the second Thursday of the month generally. You can use this handy-dandy list to check dates:_

- [ ] DCJS[65] Thu Dec 13 2018
- [ ] DCJS[66] Thu Jan 10 2019
- [ ] DCJS[67] Thu Feb 14 2019
- [ ] DCJS[68] Thu Mar 14 2019
- [ ] DCJS[69] Thu Apr 11 2019
- [ ] DCJS[70] Thu May 09 2019
- [x] DCJS[71] Thu Jun 13 2019
- [x] DCJS[71] Thu Jul 13 2019
- [x] DCJS[71] Thu Aug 13 2019
- [x] DCJS[71] Thu Sep 13 2019

**Comment by jakerella** [comment]
Sounds neat! I think we've got talks through September right now (but people have dropped before). I think we could expand this just a bit to get to 45 minutes with an intro on what graphQL is?

**Comment by ksteigerwald** [comment]
I can flush this out to 45 minutes no problem. I've been working with Hasura quite a bit now so will have plenty to add to my original presentation. Also, if you need to push this to October/November, thats fine too.

**Comment by lizafloyd** [comment]
Hi @ksteigerwald ! If you're still interested in giving this talk, we'd love to get you on the schedule. What is your availability for Nov or Dec? Thanks for your interest!

**Comment by ksteigerwald** [comment]
I will be away over veterans day weekend, but free the rest of November. December I will be free until the last week.

**Comment by jakerella** [comment]
Hi Kris! December is actually going to be a NationJS after party versus a normal meetup. That said, January is open, thoughts?

**Comment by ksteigerwald** [comment]
Hello Jordan. December is meant for partying January will work fine. This is good as I am presenting on this topic again at work. I should have some fresh content and examples.

**Comment by jakerella** [comment]
Nice! You're scheduled for January 9!

@lizafloyd ^

**Comment by jakerella** [comment]
Hey @ksteigerwald Can you expand on the talk abstract at all? I'm creating the meetup event for January 9 and wanted to give a little more context for attendees.

**Comment by ksteigerwald** [comment]
Yes, that could use some polish. I will post an updated abstract tonight!

**Comment by ksteigerwald** [comment]
@jakerella Updated. Let me know if this works or not.

**Comment by jakerella** [comment]
Thanks! Looks good

**Comment by jakerella** [comment]
Hi Kris! I'm guessing you saw this, but the January meetup was posted. Can you be sure to RSVP?

https://www.meetup.com/DC-JavaScript/events/267117039/

**Comment by ksteigerwald** [comment]
Guessing you saw, but confirming here that I RSVP on meetup.com

**Comment by jakerella** [comment]
Thanks!

**Comment by ksteigerwald** [comment]
@jakerella Someone on meetup was confused over the title given it included 'Weekend'. I updated the title in the hope to make things more clear.
