### ISSUE TITLE
Tour de Bikeshare: Setting World Records with JavaScript

### ISSUE THREAD

**Issue by kylehill** [dcjs/talks#76]
**Your Name:** Kyle Hill
**Your twitter handle:** @kylehill
**A few words about yourself:** Hi! I've been a JS dev and code school instructor in DC for like, a decade. I _just_ gave this talk [at JSConf in August 2019](https://2019.jsconf.us/speakers/kyle-hill) and it went over super well! Since it's foundationally about DC, I want to give it locally too!
**Talk title:** Tour de Bikeshare: Setting World Records with JavaScript

**Talk abstract:**  
In the summer of 2019, a somewhat out-of-shape software developer had a terrible idea — to use JavaScript to derive the algorithm that powers Washington DC’s bikeshare system and then try to set a one day record helping other people get where they want to go.

In this talk, we’ll learn about how humans can deduce machine learning, how you can turn yourself into your own API, and about how 250 years of history and a few million years of geology influences everyone that lives, works, and plays in our nation’s capital.

Can our heroic speaker overcome DC’s climate, the L’Enfant Plan, AND his own laziness to break a world record? Probably not, but let’s find out together!

**Expected length:** Not too much more than 30 minutes

**Available months:** Pretty much whenevs

**Comment by jakerella** [comment]
Sounds great! Our folks will take a look to see when we could do this.

**Comment by lizafloyd** [comment]
Hi @kylehill ! We'd love to get you on the calendar if you're still interested in giving this talk, sounds great! What's your availability for the next couple of months? Our dates would be Oct 10, Nov 14, Dec 12 I believe. Confirming those dates now.

**Comment by kylehill** [comment]
Sure! November 14th actually works pretty well for me -- I'd need to request the evening off from my teaching gig, but if we can get that confirmed soon it shouldn't be a problem.

**Comment by lizafloyd** [comment]
@kylehill Great! We'd love to have you! I'll get started on the event posting -- could I ask you for a few sentences of bio on you? What code bootcamp you teach for, what your hobbies are in your free time, etc? Thanks so much, can't wait for your talk!

**Comment by kylehill** [comment]
Sure!

Kyle Hill has been a developer, instructor, manager, and all-around JavaScript person for, like, a decade at this point. He's currently teaching at Thinkful, an online code school. When he's not following through on various terrible ideas, Kyle likes hoppy beers, being outdoors, pub trivia, his spouse, and one of his two cats. He dislikes his other, much more garbage cat.

**Comment by lizafloyd** [comment]
This is PERFECT. Thanks @kylehill , posting the event today. We'll see you between 6:30 and 7 to get you set up to present on Nov 14th! Thanks so much for volunteering, I can't wait 😄
