### ISSUE TITLE
Bio and headshot?

### ISSUE THREAD

**Issue by jakerella** [dcjs/talks#8]
Do we want to post a speaker bio and headshot with meetup events? If so we can add that to our issue template for talk suggestions.

**Comment by elgreg** [comment]
Headshot is asking too much, IMHO.

**Comment by asabaylus** [comment]
I only go the sexy speakers

**Comment by asabaylus** [comment]
Sorry bad joke. I don't think we need headshots.

**Comment by jakerella** [comment]
That's cool... but bio?

**Comment by elgreg** [comment]
☝️
