### ISSUE TITLE
Debugging Your Brain Workshop

### ISSUE THREAD

**Issue by caseywatts** [dcjs/talks#82]
**Your Name:** Casey Watts
**Your twitter handle:** @kyloma
**A few words about yourself:**
Casey Watts is the author of [Debugging Your Brain](https://www.debuggingyourbrain.com) (DYB), a clear applied psychology book and a concise self-help book. His book brings together two of his backgrounds: psychology and software development. Casey studied neurobiology at Yale University, and he is a co-author on [several neurobiology papers](https://pubmed.ncbi.nlm.nih.gov/?term=Watts+and+Schafe). He has also worked in software development for 10 years, including at [Heroku](https://blog.heroku.com/authors/casey-watts). Casey can play ten musical instruments, and he owns one in every color of the rainbow (most recently a white accordion). Casey has been an active member of the DC Tech community since 2015. 

**Talk title:**
Debugging Your Brain Workshop

**Talk abstract:**  
The human brain is buggy. Sometimes your mind distorts reality, gets frustrated with shortcomings, and spirals out of control. With practice, you can debug your brain. Catch those distortions of reality, transform those frustrations into insight, and short-circuit those downward spirals.

In this workshop you will get a chance to practice each core idea from Casey’s book [Debugging Your Brain](https://www.debuggingyourbrain.com): Modeling The Brain, Cognitive Behavioral Therapy, Introspection, Identifying Inputs, Experience Processing, Experience Validation, and Cognitive Restructuring.

Debugging Your Brain is available in all three formats: printed book, eBook and audiobook: debuggingyourbrain.com

**Expected length:** 60min

**Availability:**  
any time!

_We meet on the second Thursday of the month generally. You can use this handy-dandy list to check dates:_  
- [ ] DCJS[77] Thu Feb 13 2020
- [ ] DCJS[78] Thu Mar 12 2020
- [ ] DCJS[79] Thu Apr 09 2020
- [ ] DCJS[80] Thu May 14 2020
- [ ] DCJS[81] Thu Jun 11 2020
- [ ] DCJS[82] Thu Jul 09 2020
- [ ] DCJS[83] Thu Aug 13 2020
- [ ] DCJS[84] Thu Sep 10 2020
- [ ] DCJS[85] Thu Oct 08 2020
- [ ] DCJS[86] Thu Nov 12 2020
- [ ] DCJS[77] Thu Dec 10 2020

**Comment by asabaylus** [comment]
Thanks @caseywatts you rock! :shipit:
