### ISSUE TITLE
Rethinking Front End APIs: authoring a library with a declarative API

### ISSUE THREAD

**Issue by jameslaneconkling** [dcjs/talks#83]
**Your Name:** James Conkling
**Your twitter handle:** @jamesconkling
**A few words about yourself:** I'm a developer working at Sayari, a DC-based technology company tracking illicit financial networks. My background covers web development, cartography, and data visualization.

**Talk title:** Rethinking Front End APIs: authoring a library with a declarative API

**Talk abstract:** 
As a multi-paradigm language, javascript permits a wide range of different coding styles and varied approaches to organizing library APIs. When designing our network visualization library [trellis](github.com/sayari-analytics/trellis), our team at Sayari took inspiration from projects like React and Kubernetes and D3 to create a fully declarative, stateless API that's easy to use and makes very few assumptions about the project it's embedded in. In this talk, I'll describe our thinking behind these choices, and demonstrate how projects like Trellis with declarative APIs contrast with data visualization libraries with imperative interfaces.

[A longer description of what you'd like to speak about goes here... you can revise this over time! This should be 4-5 sentences probably]

**Expected length:** 30min - 45min

**Availability:**  
- [x] DCJS[84] Thu Jun 10 2021
- [x] DCJS[85] Thu Jul 08 2021
- [x] DCJS[86] Thu Aug 12 2021
- [x] DCJS[87] Thu Sep 09 2021
- [ ] DCJS[88] Thu Oct 14 2021
- [x] DCJS[89] Thu Nov 11 2021
- [x] DCJS[90] Thu Dec 09 2021
- [x] ...

**Comment by jakerella** [comment]
Thanks James! This looks interesting, I thin k we might not have time to get something together in July, are you open to August 12? I'll ping the other hosts and check that we don't have anyone set for that date yet.

**Comment by jameslaneconkling** [comment]
Yeah, took another look at my calendar and actually August should work for me, as would September.

**Comment by jakerella** [comment]
Let's plan on August for now. We'll get a meetup setup for it, but probably not for a week or two.

**Comment by jakerella** [comment]
@jameslaneconkling Hey there! So, we scheduled the meetup, but it looks like none of the hosts will be able to be online on that evening now. We'd like to postpone to the September meetup date, the 9th of September. Does that work for you?

**Comment by jakerella** [comment]
@jameslaneconkling Haven't heard back from you. We've cancelled the August meetup due to none of us being around to host. Will you be able to present on September 9?

**Comment by jameslaneconkling** [comment]
@jakerella apologies, missed that last message! Yes, Sept 9 works for me. Thanks for organizing this.

**Comment by jakerella** [comment]
Great, thanks @jameslaneconkling ! I'll post here when we have the September event up on Meetup.com

**Comment by jakerella** [comment]
All set, thanks again!

https://www.meetup.com/DC-JavaScript/events/279974569/

**Comment by jakerella** [comment]
Hey @jameslaneconkling! I don't see you registered for the meetup event, can you be sure to do so? That's how we'll send out Zoom information.

https://www.meetup.com/DC-JavaScript/events/279974569/

**Comment by jameslaneconkling** [comment]
done

**Comment by jakerella** [comment]
Thanks again James! Great talk.
